//Script GUID:cf1f5f59-c6cc-46d6-87e6-94e96d27eb1a
//Used for tracking history
//Script GUID:4f7170db-9e1b-435a-9440-7701ab8c7f23
//Used for tracking history
/*
This script collects the monthly view data from all surface channels for unified funnel report.

*/
//reference for SchemaExtractor and SchemaOutputter
REFERENCE @"/shares/adCenter.RnR.Daily_SLA/data/AdSelection/Lib/ScopeExtras.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreaker.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreaker.dll.config";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreakerServices.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreakerServicesWrapper.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/TrademarkReplacements.txt";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/ADC-langwrbk.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1028noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1030noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1031noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1033noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1035noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1036noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1040noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1041noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1042noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1043noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1044noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1046noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1053noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/2052noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/3082noise.bin";
//REFERENCE @"/shares/bingads.algo.prod.adsplus/ProdAdsPlusShare/Team/AdsPlus/SangamCommon/DLL/Newtonsoft.Json.dll";
//REFERENCE @"/shares/bingads.algo.adsplus/AdsPlusDataShare/Team/Gene/ForAether/bin/AdPredictor.ScopeUtils.dll";

USING ExpLib REFERENCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/ExpLib.exe";

USING System.Collections.Specialized;
USING System.Text.RegularExpressions;
USING System.Threading;
USING System.Linq;
USING ExpLib;
REFERENCE @"/shares/searchDM/distrib/released/FrontEndUtil/FrontEndUtil.dll"; 
RESOURCE @"/shares/searchDM/distrib/released/FrontEndUtil/GetHashUtil.dll";

REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/AbacusExpScopeLib.dll";  // GenericExeInvokingProcessor
USING AbacusExpScopeLib;
REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/ScopeExtension.dll";
USING Microsoft.AdCenter.RnR.Relevance.ScopeExtension;

// Word Breaker
REFERENCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/ICSharpCode.SharpZipLib.dll";
REFERENCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/Microsoft.AdCenter.AlteredQuery.dll";
RESOURCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/EnFrWordBreaker.zip";

REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/PegBinGenerationUtility.dll";  // GenericAdaptor
USING PegBinGenerationUtility;

REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/RelevanceLibrary.dll";  // BinFileUtilities.GetMurmurHash
USING RelevanceLibrary;
REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/mytest.dll";
RESOURCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/IPXDatapipelineUtil.dll";
REFERENCE "/shares/bingads.algo.prod.adsplus/ProdAdsPlusShare/Team/AdsPlus/Annotation/16128_HttpsUXFeature/References/System.Web.dll";
REFERENCE @"System.IO.Compression.dll";
REFERENCE @"System.IO.Compression.FileSystem.dll";
REFERENCE @"System.Drawing.dll";

// Input Params
#DECLARE RunDate DateTime = DateTime.Parse(@"@@RunDate@@");
#DECLARE OutputFolder string = "/local/Users/xucha/Image/ImgSample/";
#DECLARE StreamExpiry string = "60";
#DECLARE SnapshotViewType int = 1;

// Modules and Views
MODULE "/shares/bingads.algo.prod.adinsights/data/AdInsightMeasurement/Common/modules/RecommendationMeasurement.module" AS RecMod;
MODULE "/shares/bingads.algo.prod.adinsights/data/shared_data/AdvertiserEngagement/Metallica/prod/CommonDataFeed/Modules/C2C.module" AS C2C;
#DECLARE UnifiedLayerPerf string = "/shares/bingAds.BI.OI/AdsOI/DemandMetrics/Views/UnifiedLayerPerf.view";

// Libraries
//REFERENCE "/shares/bingads.algo.prod.adinsights/data/AdInsightMeasurement/Common/dlls/OpportunityTypeLib.dll";
//REFERENCE @"OpportunityTypeLib.dll";
//USING OpportunityTypeLib;
//USING Newtonsoft.Json.Linq;

// Constants
#DECLARE ViewWindow int = 0;

#DECLARE GeneratedStartDate DateTime = @RunDate.AddDays(1 - @RunDate.Day);
#DECLARE GeneratedEndDate DateTime = @RunDate;
#DECLARE GeneratedDuration int = 1 + (@GeneratedEndDate - @GeneratedStartDate).Days;

#DECLARE ViewStartDate DateTime = @GeneratedStartDate;
#DECLARE ViewDuration int = @GeneratedDuration + @ViewWindow;
#DECLARE ViewEndDate DateTime = @ViewStartDate.AddDays(@ViewDuration - 1);
#DECLARE ViewStartDateStr string = @ViewStartDate.ToString("yyyy-MM-dd");
#DECLARE ViewEndDateStr string = @ViewEndDate.ToString("yyyy-MM-dd");
#DECLARE CurrentDataStrforImage string = @RunDate.ToString("yyyy_MM_dd");


// Input Streams
#DECLARE AccSegRoot string = "/shares/bingads.algo.prod.adinsights/data/shared_data/DemandResources/AccountSegment/";
#DECLARE AccSegPath string = string.Format("{0}/{1:yyyy/MM}/AccountSegment_{1:yyyy-MM-dd}.ss", @AccSegRoot, @GeneratedEndDate);
#DECLARE C2CMasterView string = "/shares/adCenter.BICore.upload/prod/C2C/Views/MasterView/C2CMasterView.view"; 

#DECLARE UcmTacticInfoFile string = "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/UCM/Data/UcmTacticInfo.csv";
#DECLARE CDLFolder string = "/shares/bingads.algo.prod.adinsights/data/shared_data/AdvertiserEngagement/Metallica/prod/CommonDataFeed/";
#DECLARE AccountVertical string = @CDLFolder + "/Modules/AccountVertical.view"; // Account vertical
#DECLARE UnifiedLayerDemandView string = @"/shares/bingAds.BI.OI/AdsOI/DemandMetrics/Views/UnifiedLayerDemand.view"; 

// FinalUrlWLP
#DECLARE Data string = @"/local/Users/xucha/Image/ImgSample/SampleDataByRandomAccount_DistActvieAssetWAccountWdoc_2025-11-09_5K.ss";

//Output
#DECLARE OutputData string = @"/local/Users/xucha/Image/ImgSample/SampleDataByRandomAccount_DistActvieAssetWAccountWdocwTextEnhance_2025-11-09_5K.ss";
#DECLARE Stat string = @"/local/Users/xucha/Image/ImgSample/SampleDataByRandomAccount_DistActvieAssetWAccountWdocwTextEnhance_2025-11-09_5K_stat.ss";
Data =
    SSTREAM @Data;
Stat =     
    SELECT  
              "Before" AS Name,
              COUNT(DISTINCT AccountId) AS Accounts,
              COUNT(DISTINCT CampaignId) AS Campaigns,
              COUNT(DISTINCT AdId) AS Ads,
              COUNT(DISTINCT AssetId) AS Assets,
              COUNT(DISTINCT FinalUrl) AS Urls,
              COUNTIF(Text != "") AS WText 
     FROM Data;


//Read ImgAssets
Ads_SnapShot =
    SELECT AccountId,
           CampaignId,
           OrderId,
		   AdId,
		   DestinationURL,
		   FinalURL,
           Domain
    FROM
    (
        VIEW @UnifiedLayerDemandView
        PARAMS
        (
            ViewName = "Ads",
            LogDate = @RunDate
        )
    );

Ads_SnapShot =
    SELECT DISTINCT *,
                    IF(string.IsNullOrEmpty(FinalURL), DestinationURL, FinalURL) AS FinalUrl
    FROM Ads_SnapShot
    HAVING FinalUrl.Length > 2;

Ads_SnapShot =
    SELECT *.Except(FinalUrl),
           IF(FinalUrl.ToLower().StartsWith("http"), FinalUrl, "http://"+FinalUrl) AS FinalUrl
    FROM Ads_SnapShot;



AdUrl = SELECT FIRST(AdId) AS AdId,
              FinalUrl
        FROM Ads_SnapShot;

AdUrl =
    SELECT A.*
    FROM AdUrl AS A
    LEFT SEMIJOIN
        Data AS B
        ON A.FinalUrl == B.FinalUrl;

//Prepare text assets
AdAssets =
    SELECT DISTINCT
        (long) AdId AS AdId,
        AssetId
    FROM
    (
        VIEW @C2CMasterView
        PARAMS
        (
            ViewName = "AdAsset_Raw",
            ViewType = @SnapshotViewType,
            RequestEndDateUtc = @RunDate,
            RequestEndHourUtc = 23,
            ViewMode = "PROD",
            DataMode = "PROD"
        )
    )
    WHERE LifeCycleStatusId == 71 AND IsSoftDeleted != true AND AdId != null AND AssetId != null
        AND AdAssetAssociationTypeId IN (11,12,32,33,34);

AdUrl =
    SELECT A.*,
           B.AssetId
    FROM AdUrl AS A
    INNER JOIN
        AdAssets AS B
        ON A.AdId == B.AdId;

// text asset detail
TextAssetsDetails =
    SELECT AssetId,
        AssetText	      
    FROM
    (
        VIEW @C2CMasterView
        PARAMS
        (
            ViewName = "TextAsset_Raw",
            ViewType = @SnapshotViewType,
            RequestEndDateUtc = @RunDate,
            RequestEndHourUtc = 23
        )
    );
TextAssetsDetails = SELECT AssetId,
                FIRST(AssetText) AS AssetText
                FROM TextAssetsDetails;

AdUrl = 
    SELECT A.*,
    B.AssetText
    FROM AdUrl AS A
    INNER JOIN TextAssetsDetails AS B 
    ON A.AssetId == B.AssetId;
TextAssets = 
    SELECT FinalUrl,
        FIRST(AdId) AS AdId,
        string.Join("[SEP]", ARRAY_AGG(AssetText)) AS Text
    FROM AdUrl;

Data0 =
    SELECT AccountId, CampaignId, AdId, AssetId, FinalUrl, Tag, AssetType, CampaignSpend, CampaignImpr, CampaignClick, Segment, Vertical_L1, Vertical_L2, Vertical_L3, Vertical_L4,
    ImgUrl,OriginalMediaWidth,OriginalMediaHeight,Text,url_id,doc
    FROM Data
    WHERE Tag != "ImgExtension";

Data1 =
    SELECT *
    FROM Data
    WHERE Tag == "ImgExtension";

Data1 =
    SELECT 
           A.AccountId,
           A.CampaignId,
           B.AdId??(long) 0 AS AdId,
           A.AssetId,
           A.FinalUrl,
           A.Tag,
           A.AssetType,
           A.CampaignSpend,
           A.CampaignImpr,
           A.CampaignClick,
           A.Segment,
           A.Vertical_L1,
           A.Vertical_L2,
           A.Vertical_L3,
           A.Vertical_L4,
           A.ImgUrl,
           A.OriginalMediaWidth,
           A.OriginalMediaHeight,
           B.Text??"" AS Text,
           A.url_id,
           A.doc
    FROM Data1 AS A
    LEFT OUTER JOIN
        TextAssets AS B
        ON A.FinalUrl == B.FinalUrl;

Data =
    SELECT *
    FROM Data0
    UNION ALL
    SELECT *
    FROM Data1;

Stat =     SELECT * FROM Stat
    UNION ALL
    SELECT  
              "After" AS Name,
              COUNT(DISTINCT AccountId) AS Accounts,
              COUNT(DISTINCT CampaignId) AS Campaigns,
              COUNT(DISTINCT AdId) AS Ads,
              COUNT(DISTINCT AssetId) AS Assets,
              COUNT(DISTINCT FinalUrl) AS Urls,
              COUNTIF(Text != "") AS WText 
     FROM Data;


OUTPUT Data TO SSTREAM @OutputData
WITH STREAMEXPIRY @StreamExpiry;

OUTPUT Stat TO SSTREAM @Stat
WITH STREAMEXPIRY @StreamExpiry;


