//Script GUID:0cedbe16-0f84-407d-a623-0d72f39948cb
//Used for tracking history
//Script GUID:d93aa970-fc91-466c-9fe6-2e340396c8c9
//Used for tracking history

//DLL 
REFERENCE @"/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/Ranking/MurmurHashCSharpDll.dll";
RESOURCE @"/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/Ranking/MurmurHashDll.dll";
REFERENCE @"/shares/bingads.algo/data/Team/ClickPrediction/Padjust/Resources/Relevance.ScopeLib.dll";
REFERENCE "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/Stemmer.dll";
RESOURCE "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/Microsoft.BingNlPlatform.Fst.dll";
RESOURCE "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/Microsoft.BingNlPlatform.Fst.Wrapper.dll";
RESOURCE "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/english.morph.known.fst";
RESOURCE "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/AdcopyGeneration/Resources/allowedInflexions.txt";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreaker.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreaker.dll.config";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreakerServices.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreakerServicesWrapper.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/TrademarkReplacements.txt";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/ADC-langwrbk.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1028noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1030noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1031noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1033noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1035noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1036noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1040noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1041noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1042noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1043noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1044noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1046noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1053noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/2052noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/3082noise.bin";
USING ExpLib REFERENCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/ExpLib.exe";
REFERENCE "/shares/bingads.algo.prod.adinsights/data/shared_data/AdvertiserEngagement/Metallica/prod/CommonDataFeed/Modules/CommonDataLayerLib.dll";

REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/System.ObjectModel.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/System.Dynamic.Runtime.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/Microsoft.CSharp.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/System.Runtime.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/SemanticHtml.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/Microsoft.Bing.HashUtil.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/DCVisualDomParser.dll";
REFERENCE @"/shares/WebDataPlatform/local/CleanBody/Snapshots/Resources/v3_3_nwp/Google.Protobuf.dll";

#DECLARE RecommendationMeasurementModulePath string = @"/shares/bingads.algo.prod.adinsights/data/AdInsightMeasurement/Common/modules/RecommendationMeasurement.module";
MODULE @RecommendationMeasurementModulePath AS RecModule;

// Url Normalization and join WebPlatform SD
// This module reads an input list of urls and provides followings output: 1. Normalized url: We transform url using the normalization rules. The idea here is strip the parameters that are deemed non-useful by the normalization team so as to be more efficient with our index space. Note all the urls in IndexGeneration system onwards have been normalized with these rules. For detailed info see (https://www.bingwiki.com/URL_Normalization) 2. RetroIndexKeyUrl: this is retroindexkey version of normalized url for joining with retroindex.3. HutHash: this is hash of normalized url that is  the identifier of document in many IS stacks. 
REFERENCE "/shares/searchWebLoad/RetroIndex/bin/ManagedUrlNormalizer.dll";
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/NativeUrlNormalizer.dll";
REFERENCE "/shares/searchWebLoad/RetroIndex/bin/DpimScopeCommon.dll";
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/DpimFormatting.dll";
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/UrlNormalizerConfig.DP.ini";          
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/UrlNormalizeRules.txt";               
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/tld.txt";                             
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/UrlNormalizePatterns.tsv";            
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/UrlNormalizeRegexPatterns.tsv";       
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/DpimFormatting.cfg";
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/full_CB.wsv";
REFERENCE "/shares/searchWebLoad/RetroIndex/bin/ManagedUrlNormalizer.dll";
RESOURCE "/shares/searchWebLoad/RetroIndex/bin/NativeUrlNormalizer.dll";

//Resource and Reference
REFERENCE "/shares/bingads.platform.prod.indexgen/Data/IG_runtime_resources/common/FrontEndUtil.dll";
RESOURCE "/shares/bingads.platform.prod.indexgen/Data/IG_runtime_resources/common/GetHashUtil.dll";
#DECLARE SD_CORPUS string = "/shares/bingads.platform.prod.indexgen/Data/publish/SDP-Prod-Ch1/LPDU/Views/SD_Corpus.ss.view";

//Param
#DECLARE AddTagToSD string = "false"; //@"@@AddTagToSD@@";   //"true" or "false"
#DECLARE ToStream string = "true"; //@"@@ToStream@@";   //"true" or "false"

//Input
#DECLARE Input1 string = @"/local/Users/xucha/Image/ImgSample/SampleDataByRandomAccount_DistActvieAssetWAccount2025-11-09_5K.ss";
//Output
#DECLARE Sug_SD string = @"/local/Users/xucha/Image/ImgSample/SampleDataByRandomAccount_DistActvieAssetWAccountWdoc_2025-11-09_5K.ss";
#DECLARE Stat string = @"/local/Users/xucha/Image/ImgSample/SampleDataByRandomAccount_DistActvieAssetWAccountWdoc_2025-11-09_5K_stat.ss";


Input = 
    SELECT *.Except(Rand,Rid)
    FROM (SSTREAM @Input1);


Input =
    SELECT *,
           !string.IsNullOrEmpty(FinalUrl) && FinalUrl != "!"? FrontEndUtil.CURLUtilities.GetCBUrlHash(FinalUrl) : "" AS url_id
    FROM Input;



Stat = 
    SELECT "0.0 Distinct FinalUrl in Input" AS Name,
           COUNT(DISTINCT FinalUrl) AS Value
    FROM Input;

Input_url_id =
    SELECT DISTINCT url_id
    FROM Input;

Stat = 
    SELECT *
    FROM Stat
    UNION ALL
    SELECT "0.1 Distinct url_id in Input_url_id" AS Name,
           COUNT(DISTINCT url_id) AS Value
    FROM Input_url_id;

sdcorpus = 
    SELECT url_id,
           FIRST(SemanticHtml) AS SemanticHtml 
    FROM (VIEW @SD_CORPUS) 
    WHERE !String.IsNullOrEmpty(url_id) AND SemanticHtml != null AND SemanticHtml.Length > 0;

[PARTITION=(PARTITIONCOUNT=5000)]
sdcorpus = 
    SELECT DISTINCT A.url_id,
           B.SemanticHtml
    FROM Input_url_id AS A
    INNER JOIN sdcorpus AS B
    ON A.url_id==B.url_id;

Stat = 
    SELECT *
    FROM Stat
    UNION ALL
    SELECT "1.0 Count url_id after joined sdcorpus" AS Name,
           COUNT(DISTINCT url_id) AS Value
    FROM sdcorpus;

sdcorpus =
    PROCESS sdcorpus
    USING SDStreamProcessor(@"
    PrimaryContentNoTitleNoHeadingNoParagraph:^InvisibleText,^Heading,^Paragraph,^VisualTitle,^DocumentTitle;
    VisualTitle:VisualTitle,^InvisibleText;
    DocumentTitle:DocumentTitle,^InvisibleText;
    Heading:Heading,^InvisibleText,^VisualTitle,^DocumentTitle;
    Paragraph:Paragraph,^InvisibleText
    ")
    HAVING !PrimaryContentNoTitleNoHeadingNoParagraph.StartsWith("Error.") AND 
           !PrimaryContentNoTitleNoHeadingNoParagraph.StartsWith("redir.php") AND 
           !PrimaryContentNoTitleNoHeadingNoParagraph.StartsWith("An error occurred");

#IF( @AddTagToSD.ToLower() == "true" )
    sdcorpus_with_name =
        SELECT DISTINCT url_id,
               GenerateDoc.OrganizeSD(DocumentTitle, VisualTitle, Heading, Paragraph, PrimaryContentNoTitleNoHeadingNoParagraph) AS doc
        FROM sdcorpus;
#ELSE
    sdcorpus_with_name =
        SELECT DISTINCT url_id,
                        DocumentTitle + ";" + VisualTitle + ";" + Heading + ";" + Paragraph + ";" + PrimaryContentNoTitleNoHeadingNoParagraph AS doc
        FROM sdcorpus;
#ENDIF

Stat = 
    SELECT *
    FROM Stat
    UNION ALL
    SELECT "2.0 Distinct Url Id in sdcorpus_with_name" AS Name,
           COUNT(DISTINCT url_id) AS Value
    FROM sdcorpus_with_name;

Sug_SD =
    SELECT A.*,
           B.doc
    FROM Input AS A
         INNER JOIN
             sdcorpus_with_name AS B
         ON A.url_id == B.url_id;

Sug_SD =
    SELECT DISTINCT *
    FROM Sug_SD
    WHERE doc.Length > 5;

Stat = 
    SELECT *
    FROM Stat
    UNION ALL
    SELECT "3.0 DISTINCT url_id in Sug_SD" AS Name,
           COUNT(DISTINCT url_id) AS Value
    FROM Sug_SD
    UNION ALL
    SELECT "3.1 Number of Rows in Sug_SD" AS Name,
           COUNT(*) AS Value
    FROM Sug_SD;

//Lang
//HumpbackV2
//https://microsoftapc.sharepoint.com/teams/binguf/SitePages/Onboarding-to-Offline-Query-Language-Detection-Packages-Humpback-V2-(fasttext).aspx
//MODULE "/shares/BingUF/BingUFLibs/LanguageDetectorV2/1.3/LanguageDetectorV2.module" AS HumpbackV2;
/*
Sug_SD = 
    SELECT *,
           LanguageDetectorV2Scope.DetectFirstLang(doc) AS Language
    FROM Sug_SD;
*/

#IF(@ToStream.ToLower() == "true" )
    OUTPUT Sug_SD TO SSTREAM @Sug_SD;

    OUTPUT Stat TO SSTREAM @Stat;                                     
#ELSE
    OUTPUT Sug_SD TO @Sug_SD;

    OUTPUT Stat TO @Stat;
#ENDIF

    
 
#CS
using SemanticHtml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using ScopeRuntime;
using System.Text.RegularExpressions;
using Microsoft.SCOPE.Types;
 
public static class StringExt{
  public static string WithMaxLength(string value, int maxLength)
  {
    if(String.IsNullOrEmpty(value)){
        return "";
    }else{
      return value.Substring(0, Math.Min(value.Length, maxLength));
    }
  }
}
 
public class ColSpec
{
  public string colname;
  public List<string> include;
  public List<string> exclude;
 
  public ColSpec(string name, string spec)
  {
    colname = name.Trim();
    include = new List<string>();
    exclude = new List<string>();
 
    string[] specsplit = spec.Split(',');
    foreach(var sp in specsplit){
      string sptrim = sp.Trim();
 
      // Check if annotation exclusion condition
      if(sptrim.StartsWith("^")){
        exclude.Add(sptrim.Substring(1));
      }
      else{
        include.Add(sptrim);
      }
    }
  }
}
 
/*
SDStreamProcessor expects as argument a ;-separated list of column specifications.
Each column specification has the format:
  [Name of column to create]: [comma-separated list of annotations to include/exclude in block.  To exclude an annotation, precede it with ^]
 
  Examples of column specifications:
    CleansedMain: Main,^InvisibleText,^Table 
      --> This will create a column called CleansedMain that is a concatenation of all blocks of text in the document
      with annotation Main and doesn't contain the InvisibleText or Table annotations
 
    InvisibleTables: InvisibleText,Table 
      --> This will create a column called InvisibleTables that is a concatenation of all blocks of text with 
      both the InvisibleText and Table annotations
*/
 
public class SDStreamProcessor : Processor
{
  public override bool RowLevelProcessor { get { return true; } }
 
  // Generating output schema
  public override Schema Produces(string[] requestedColumns, string[] args, Schema inputSchema)
  {
    string[] columnmap = args[0].Split(';');
 
    Schema sch = inputSchema.CloneWithSource();
    foreach (string col in columnmap)
      sch.Add(new ColumnInfo(col.Split(':')[0].Trim(), ColumnDataType.String));
    return sch;
  }
 
  public Regex rgx = new Regex(@"^([^a-z]|((price|new offer|out|of|review|star|under|above|to|cdn|up|save|reg|regular|used|new offer|result|like|post|folower|subscriber|am|pm|monday|tuesday|wednesday|thursday|friday|saturday|sunday)s?))+$", RegexOptions.Compiled);
  char[] delimiters = new char[] {' ', '\r', '\n' };
 
  public bool badregex(string text){
    bool ismatch = false;
    text = text.ToLower().Trim();
  
    // Remove text blocks with < 3 characters
    ismatch |= (text.Length < 3);
 
    // Remove short blocks with $ sign (price info)
    ismatch |= ((text.Split(delimiters,StringSplitOptions.RemoveEmptyEntries).Length < 7) & text.Contains("$")); 
  
    // Contains only non-alphabetical characters or invalid phrases
    if(text.Length < 100)
      ismatch |= rgx.IsMatch(text);
 
    return ismatch;
  } 
 
  public override IEnumerable<Row> Process(RowSet input, Row output, string[] args)
  {
    // Initialize all possible annotations
    var allannotations = Enum.GetValues(typeof(SemanticHtml.SemanticHtml.Types.AnnotationType)).Cast<SemanticHtml.SemanticHtml.Types.AnnotationType>().ToHashSet();
 
    // Initialize list of tuples mapping column name to annotation conditions
    List<ColSpec> columns = new List<ColSpec>();
    string[] columnmap = args[0].Split(';');
    foreach (string col in columnmap){
      string[] colsplit = col.Split(':');
      columns.Add(new ColSpec(colsplit[0], colsplit[1]));
    }
 
    int isdoc = input.Schema.IndexOf("SemanticHtml"); // Index of input SD protobuf column
 
    foreach (Row row in input.Rows)
    {
      output.Reset();
      row.CopyTo(output);
 
      byte[] semHtmlBytes = row[isdoc].Binary;
      bool validsd = true;
 
      if (null == semHtmlBytes || 0 == semHtmlBytes.Length)
      {
        validsd = false;
        foreach(var spec in columns){
          output[spec.colname].Set("");
        }
      }
 
      SemanticHtml.SemanticHtmlDocumentApi semHtml = null;
 
      try
      {
        semHtml = new SemanticHtml.SemanticHtmlDocumentApi(SemanticHtml.SemanticHtmlDocumentApi.DeserializeSemanticHtml(semHtmlBytes));
      }
      catch
      {
        validsd = false;
        foreach(var spec in columns){
          output[spec.colname].Set("");
        }
      }
         
      if(validsd){
        // initialize column outputs and hashset of textblocks
        Dictionary<string, string> outputs = new Dictionary<string, string>();
        Dictionary<string, HashSet<string>> textblocks = new Dictionary<string, HashSet<string>>();
        foreach (var spec in columns){
          outputs.Add(spec.colname, "");
          textblocks.Add(spec.colname, new HashSet<string>());
        }
         
        // iterate over all text blocks in the document
        foreach (var block in semHtml.GetTextBlocks())
        {
          int blockcount = 0;

          // gather all annotations that cover this block of text
          HashSet<string> annotations = new HashSet<string>();
 
          foreach (var aOver in semHtml.GetAnnotationsOver(block.Start, block.End, allannotations))
          {
            annotations.Add(aOver.Type.ToString());
          }
 
          // get a plain text of the entire block
          string text = semHtml.GetText(block.Start, block.End).Trim();
 
          // check annotation conditions
          foreach (var spec in columns){
            bool meetspec = true;
  
            // check block contains all include annotations
            foreach(var ant in spec.include){
              if (!annotations.Contains(ant))
                meetspec = false;
            }
            // check block doesn't contain any exclude annotations
            foreach(var ant in spec.exclude){
              if (annotations.Contains(ant))
                meetspec = false;
            }
 
            if(meetspec & !String.IsNullOrEmpty(text) & !textblocks[spec.colname].Contains(text) & (spec.colname == "PrimaryContent" | spec.colname == "InvisibleText" | !badregex(text))){
              outputs[spec.colname] += (" . " + text); //#B#
              textblocks[spec.colname].Add(text);
            }
          }
          blockcount = blockcount + 1;
          if(blockcount > 100){
            break;
          }

        }
        foreach(var spec in columns)
            output[spec.colname].Set(outputs[spec.colname].StartsWith(" . ") ? outputs[spec.colname].TrimStart('.') : outputs[spec.colname].Trim());
      }
 
      yield return output;
    }
  }
}

public static class Normalizer
{
    public static string Normalize(string s) //naive wb, only keep a-z, 0-9, ' '; 
    {
        if (string.IsNullOrEmpty(s))
            return null;

        string lowerStr = s.ToLower();
        StringBuilder normSb = new StringBuilder();
        normSb.Length = 0;

        bool lastSpace = true;
        for (int i = 0; i < lowerStr.Length; i++)
        {
            if (Char.IsLetterOrDigit(lowerStr[i]))
            {
                normSb.AppendFormat("{0}", lowerStr[i]);
                lastSpace = false;
            }
            else if (!lastSpace)
            {
                normSb.AppendFormat(" ");
                lastSpace = true;
            }
        }

        if (normSb.Length == 0)
            return null;

        return normSb.ToString().TrimEnd();
    }
}


public class GenerateDoc
{
    public static string OrganizeSD(string DocumentTitle, string VisualTitle, string Heading, string Paragraph, string PrimaryContentNoTitleNoHeadingNoParagraph)
    {
        string doc = "";
        if(DocumentTitle.Length > 2)
            doc += " -SD_DocumentTitle- " + DocumentTitle;
        if(VisualTitle.Length > 2)
            doc += " -SD_VisualTitle- " + VisualTitle;
        if(Heading.Length > 2)
            doc += " -SD_Heading- " + Heading;
        if(Paragraph.Length > 2)
            doc += " -SD_Paragraph- " + Paragraph;
        if(PrimaryContentNoTitleNoHeadingNoParagraph.Length > 2)
            doc += " -SD_PrimaryContentNoTitleNoHeadingNoParagraph- " + PrimaryContentNoTitleNoHeadingNoParagraph;
        return doc;
    }
}

#ENDCS
