//Script GUID:a703e3a4-70a2-45d6-a9a6-28defc1f0d56
//Used for tracking history
//Script GUID:4f7170db-9e1b-435a-9440-7701ab8c7f23
//Used for tracking history
/*
This script collects the monthly view data from all surface channels for unified funnel report.

*/
//reference for SchemaExtractor and SchemaOutputter
REFERENCE @"/shares/adCenter.RnR.Daily_SLA/data/AdSelection/Lib/ScopeExtras.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreaker.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreaker.dll.config";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreakerServices.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/WordBreakerServicesWrapper.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/TrademarkReplacements.txt";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/ADC-langwrbk.dll";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1028noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1030noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1031noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1033noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1035noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1036noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1040noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1041noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1042noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1043noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1044noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1046noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/1053noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/2052noise.bin";
RESOURCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/3082noise.bin";
//REFERENCE @"/shares/bingads.algo.prod.adsplus/ProdAdsPlusShare/Team/AdsPlus/SangamCommon/DLL/Newtonsoft.Json.dll";
//REFERENCE @"/shares/bingads.algo.adsplus/AdsPlusDataShare/Team/Gene/ForAether/bin/AdPredictor.ScopeUtils.dll";

USING ExpLib REFERENCE @"/shares/adCenter.RnR.Daily_SLA/data/QKPI/resources/common/ExpLib.exe";

USING System.Collections.Specialized;
USING System.Text.RegularExpressions;
USING System.Threading;
USING System.Linq;
USING ExpLib;
REFERENCE @"/shares/searchDM/distrib/released/FrontEndUtil/FrontEndUtil.dll"; 
RESOURCE @"/shares/searchDM/distrib/released/FrontEndUtil/GetHashUtil.dll";

REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/AbacusExpScopeLib.dll";  // GenericExeInvokingProcessor
USING AbacusExpScopeLib;
REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/ScopeExtension.dll";
USING Microsoft.AdCenter.RnR.Relevance.ScopeExtension;

// Word Breaker
REFERENCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/ICSharpCode.SharpZipLib.dll";
REFERENCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/Microsoft.AdCenter.AlteredQuery.dll";
RESOURCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/EnFrWordBreaker.zip";

REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/PegBinGenerationUtility.dll";  // GenericAdaptor
USING PegBinGenerationUtility;

REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/RelevanceLibrary.dll";  // BinFileUtilities.GetMurmurHash
USING RelevanceLibrary;
REFERENCE "/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/mytest.dll";
RESOURCE @"/shares/BingAds.Algo.Relevance/Team/Relevance/Libs/IPXDatapipelineUtil.dll";
REFERENCE "/shares/bingads.algo.prod.adsplus/ProdAdsPlusShare/Team/AdsPlus/Annotation/16128_HttpsUXFeature/References/System.Web.dll";
REFERENCE @"System.IO.Compression.dll";
REFERENCE @"System.IO.Compression.FileSystem.dll";
REFERENCE @"System.Drawing.dll";

// Input Params
#DECLARE RunDate DateTime = DateTime.Parse(@"@@RunDate@@");
#DECLARE OutputFolder string = "/local/Users/xucha/Image/ImgSample/";
#DECLARE StreamExpiry string = "60";
#DECLARE SnapshotViewType int = 1;

// Modules and Views
MODULE "/shares/bingads.algo.prod.adinsights/data/AdInsightMeasurement/Common/modules/RecommendationMeasurement.module" AS RecMod;
MODULE "/shares/bingads.algo.prod.adinsights/data/shared_data/AdvertiserEngagement/Metallica/prod/CommonDataFeed/Modules/C2C.module" AS C2C;
#DECLARE UnifiedLayerPerf string = "/shares/bingAds.BI.OI/AdsOI/DemandMetrics/Views/UnifiedLayerPerf.view";

// Libraries
//REFERENCE "/shares/bingads.algo.prod.adinsights/data/AdInsightMeasurement/Common/dlls/OpportunityTypeLib.dll";
//REFERENCE @"OpportunityTypeLib.dll";
//USING OpportunityTypeLib;
//USING Newtonsoft.Json.Linq;

// Constants
#DECLARE ViewWindow int = 0;

#DECLARE GeneratedStartDate DateTime = @RunDate.AddDays(1 - @RunDate.Day);
#DECLARE GeneratedEndDate DateTime = @RunDate;
#DECLARE GeneratedDuration int = 1 + (@GeneratedEndDate - @GeneratedStartDate).Days;

#DECLARE ViewStartDate DateTime = @GeneratedStartDate;
#DECLARE ViewDuration int = @GeneratedDuration + @ViewWindow;
#DECLARE ViewEndDate DateTime = @ViewStartDate.AddDays(@ViewDuration - 1);
#DECLARE ViewStartDateStr string = @ViewStartDate.ToString("yyyy-MM-dd");
#DECLARE ViewEndDateStr string = @ViewEndDate.ToString("yyyy-MM-dd");
#DECLARE CurrentDataStrforImage string = @RunDate.ToString("yyyy_MM_dd");


// Input Streams
#DECLARE AccSegRoot string = "/shares/bingads.algo.prod.adinsights/data/shared_data/DemandResources/AccountSegment/";
#DECLARE AccSegPath string = string.Format("{0}/{1:yyyy/MM}/AccountSegment_{1:yyyy-MM-dd}.ss", @AccSegRoot, @GeneratedEndDate);
#DECLARE C2CMasterView string = "/shares/adCenter.BICore.upload/prod/C2C/Views/MasterView/C2CMasterView.view"; 

#DECLARE UcmTacticInfoFile string = "/shares/bingads.algo.prod.adinsights/data/prod/pipelines/Optimization/UCM/Data/UcmTacticInfo.csv";
#DECLARE CDLFolder string = "/shares/bingads.algo.prod.adinsights/data/shared_data/AdvertiserEngagement/Metallica/prod/CommonDataFeed/";
#DECLARE AccountVertical string = @CDLFolder + "/Modules/AccountVertical.view"; // Account vertical
#DECLARE UnifiedLayerDemandView string = @"/shares/bingAds.BI.OI/AdsOI/DemandMetrics/Views/UnifiedLayerDemand.view"; 

// Output Streams
#DECLARE Stat string = string.Format("{0}/PrepareData_{1:yyyy-MM-dd}_Stat.ss", @OutputFolder, @RunDate);
#DECLARE ImgAssetsData string = string.Format("{0}/PrepareData_{1:yyyy-MM-dd}.ss", @OutputFolder, @RunDate);
#DECLARE PmaxAsset string = string.Format("{0}/PrepareData_PmaxAsset_{1:yyyy-MM-dd}.ss", @OutputFolder, @RunDate);
#DECLARE MMAAsset string = string.Format("{0}/PrepareData_MMAAsset_{1:yyyy-MM-dd}.ss", @OutputFolder, @RunDate);
#DECLARE AdsSnapshot string = string.Format("{0}/PrepareData_AdsSnapshot_{1:yyyy-MM-dd}.ss", @OutputFolder, @RunDate);
//Read ImgAssets
//Pmax:
AssetGroupAsset =
    SELECT AccountId,
           CampaignId,
           (long) AssetGroupId AS AssetGroupId,
           AssetId,
           AssetAssociationTypeId
    FROM
    (
        VIEW @C2CMasterView
        PARAMS
        (
            ViewName = "AssetGroupAssetAssociation_Raw",
            ViewType = @SnapshotViewType,
            RequestEndDateUtc = @RunDate,
            RequestEndHourUtc = 23
        )
    )
    WHERE AssetAssociationTypeId IN (32,33,34,1,2,3,4,7,9,13,31,35,63);

UrlInfo =
    SELECT AccountId,
           CampaignId,
           AssetGroupId,
           AssetGroupDataPropertyValue AS Url
    FROM
    (
        VIEW @C2CMasterView
        PARAMS
        (
            ViewName = "AssetGroupData_Raw",
            ViewType = @SnapshotViewType,
            RequestEndDateUtc = @RunDate,
            RequestEndHourUtc = 23
        )
    );

AssetGroupAsset =
    SELECT A.*,
           B.Url??"" AS FinalUrl
    FROM AssetGroupAsset AS A 
    LEFT OUTER JOIN UrlInfo AS B
    ON A.AccountId == B.AccountId AND A.CampaignId == B.CampaignId AND A.AssetGroupId == B.AssetGroupId;

AssetGroupAsset = 
    SELECT AccountId,
           CampaignId,
           AssetGroupId,
           AssetId,
           FinalUrl,
           FIRST(AssetAssociationTypeId) AS AssetAssociationTypeId
    FROM AssetGroupAsset;

OUTPUT AssetGroupAsset TO SSTREAM @PmaxAsset
WITH STREAMEXPIRY @StreamExpiry;

//Other:
AdAssets =
    SELECT DISTINCT
        AccountID AS AccountId,
        CampaignId, 
        (long) AdId AS AdId,
        AssetId,
        AdAssetAssociationTypeId AS AssetAssociationTypeId
    FROM
    (
        VIEW @C2CMasterView
        PARAMS
        (
            ViewName = "AdAsset_Raw",
            ViewType = @SnapshotViewType,
            RequestEndDateUtc = @RunDate,
            RequestEndHourUtc = 23,
            ViewMode = "PROD",
            DataMode = "PROD"
        )
    )
    WHERE LifeCycleStatusId == 71 AND IsSoftDeleted != true AND AdId != null AND AssetId != null
        AND AdAssetAssociationTypeId IN (11,12,32,33,34,1,2,3,4,5,6,7,8,9,13,14,31,35);



Ads_SnapShot =
    SELECT AccountId,
           CampaignId,
           OrderId,
		   AdId,
		   DestinationURL,
		   FinalURL,
           Domain
    FROM
    (
        VIEW @UnifiedLayerDemandView
        PARAMS
        (
            ViewName = "Ads",
            LogDate = @RunDate
        )
    );

Ads_SnapShot =
    SELECT DISTINCT *,
                    IF(string.IsNullOrEmpty(FinalURL), DestinationURL, FinalURL) AS FinalUrl
    FROM Ads_SnapShot
    HAVING FinalUrl.Length > 2;

Ads_SnapShot =
    SELECT *.Except(FinalUrl),
           IF(FinalUrl.ToLower().StartsWith("http"), FinalUrl, "http://"+FinalUrl) AS FinalUrl
    FROM Ads_SnapShot;

OUTPUT Ads_SnapShot TO SSTREAM @AdsSnapshot
WITH STREAMEXPIRY @StreamExpiry;

AdUrl = SELECT AdId,
            FIRST(FinalUrl) AS FinalUrl
        FROM Ads_SnapShot;


AdAssets = 
    SELECT DISTINCT A.*,
                    B.FinalUrl??"" AS FinalUrl
    FROM AdAssets AS A 
    LEFT OUTER JOIN AdUrl AS B 
    ON A.AdId == B.AdId;

AdAssets = 
   SELECT AccountId,
           CampaignId,
           AdId,
           AssetId,
           FinalUrl,
           FIRST(AssetAssociationTypeId) AS AssetAssociationTypeId
    FROM AdAssets;
OUTPUT AdAssets TO SSTREAM @MMAAsset
WITH STREAMEXPIRY @StreamExpiry;