[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adinsights.qwen_vl']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv
pretrained_weight_path = ./model.safetensors

# model
[microsoft/model/generation/qwen3_vl/lp_image_relevance/v1]
pretrained_name = qwen3-vl-2b-instruct-img-lp-relevance
max_gen_seq_length = 512
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast]
names = ['Date', 'AccountId', 'CampaignId', 'AssetId', 'Segment', 'FinalUrl', 'ImgUrl', 'Label', 'Adcopy', 'doc', 'Lang']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    '''
    core/process/qwen_vl/generation/inputs(
      core/process/qwen_vl/chat_template(
        [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image"
                    },
                    {"type": "text", "text": """
                    Please evaluate the relevance between an image and a URL landing page (LP). Answer with only Good, Fair, or Bad. 
                    LP: {0} 
                    Output: 
                    """.format(doc)},
                ],
            }
        ]
      ),
      core/process/image/read(ImgUrl),
    )
    ''',
    'core/process/qwen_vl/generation/labels(Label)',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    '''
    core/process/qwen_vl/generation/inputs(
      core/process/qwen_vl/chat_template(
        [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image"
                    },
                    {"type": "text", "text": """
                    Please evaluate the relevance between an image and a URL landing page (LP). Answer with only Good, Fair, or Bad. 
                    LP: {0} 
                    Output: 
                    """.format(doc)},
                ],
            }
        ]
      ),
      core/process/image/read(ImgUrl),
    )
    ''',
    'core/process/qwen_vl/generation/labels(Label)',
  ]

[core/dataset/ast/test]
names = ['Date', 'AccountId', 'CampaignId', 'AssetId', 'Segment', 'FinalUrl', 'ImgUrl', 'Label', 'Adcopy', 'doc', 'Lang']
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    core/process/qwen_vl/generation/inputs(
      core/process/qwen_vl/chat_template(
        [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image"
                    },
                    {"type": "text", "text": """
                    Please evaluate the relevance between an image and a URL landing page (LP). Answer with only Good, Fair, or Bad. 
                    LP: {0} 
                    Output: 
                    """.format(doc)},
                ],
            }
        ]
      ),
      core/process/image/read(ImgUrl),
    )
    ''',  
  ]

# process
[core/process/qwen_vl]
pretrained_name = qwen3-vl-2b-instruct-img-lp-relevance
max_seq_length = 12800
max_gen_seq_length = 512

[microsoft/process/qwen_vl/lp_image_relevance/v1]
pretrained_name = qwen3-vl-2b-instruct-img-lp-relevance
max_seq_length = 12800
max_gen_seq_length = 512

[core/process/image]
http_url = "{0}"

[core/writer/csv]
escapechar = \

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/generation/qwen3_vl/lp_image_relevance/v1
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/lm
score_fn = core/score/bleu
monitor_fns = ['core/score/bleu', 'core/score/rouge1', 'core/score/rouge2', 'core/score/rougel']
output_header = ['Date', 'AccountId', 'CampaignId', 'AssetId', 'Segment', 'FinalUrl', 'ImgUrl', 'Label', 'Adcopy', 'doc', 'Lang']
postprocess_fn = microsoft/postprocess/qwen_vl/lp_image_relevance/v1
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 2
dev_batch_size = 2
test_batch_size = 2
