[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.slab.bletchley_v1_click']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/slab/bletchley/v1/ranking]
config_type = 0.3B
projection_dim = 512
num_classes = 1
num_positions = 50

# dataset
[core/dataset/ast]
# id, image, text
names = ['query', 'slab']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(text=query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(text=slab, prefix="text_")',
    'core/process/number(1, dtype="int", key="pos_ids")',
    'core/process/number(1, dtype="int", key="type_ids")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# task
[core/task/supervised]
model = microsoft/adsplus/slab/bletchley/v1/ranking
dataset = core/dataset/ast

monitor_fns = ['core/score/auc']
output_header = ['query', 'slab']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 8
test_batch_size = 128