[core/cli]
task_name = core/task/supervised
cache_dir = ./cache
test_file = ./test.tsv

# model
[core/model/matching/clip]
pretrained_name = clip-vit-large-patch14
projection_dim = 768

# dataset
[core/dataset/ast/test]
names = ['text', 'image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/clip/classification(text, core/process/image/read(image))',
  ]

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

# process
[core/process/clip]
pretrained_name = clip-vit-large-patch14
max_seq_length = 77

[core/process/classification]
act_fn = None

# task
[core/task/supervised]
model = core/model/matching/clip
dataset = core/dataset/ast
output_header = ['text', 'image']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128
