[core/cli]
task_name = core/task/supervised
cache_dir = ./cache
output_folder = ./mask_images
test_file = ./test.tsv

# model
[core/model/dpt]
pretrained_name = dpt-large

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/dpt/inputs(core/process/image/read(image))'
  ]

# process
[core/process/dpt]
pretrained_name = dpt-large

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

[core/process/segmentation]
output_folder = ${core/cli:output_folder}
http_url = http://0.0.0.0:11231/?name={0}

# task
[core/task/supervised]
model = core/model/dpt
dataset = core/dataset/ast
output_header = ['image']
postprocess_fn = core/postprocess/segmentation/mask
writer = core/writer/csv

output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 32
