[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.bletchley']
output_file = ./output.txt
test_file = ./test.tsv

# model
[microsoft/model/classification/bletchley/v3/image]
config_type = 2.5B
projection_dim = 1024
freeze_base_model = False
num_classes = 23
pretrained_weight_path = https://unitorchazureblob.blob.core.windows.net/shares/models/adsplus/image/pytorch_model.bletchley.v3.cate.2.2502.bin

# dataset

[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v3/image_classification(core/process/image/read(image))',
  ]

# process
[microsoft/process/bletchley/v3]
max_seq_length = 36

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

[core/process/classification]
act_fn = softmax
id2label = {
    0: "Sports & Fitness",
    1: "Home & Garden",
    2: "Apparel",
    3: "Others",
    4: "Food & Groceries",
    5: "Vehicles",
    6: "Beauty & Personal Care",
    7: "Hobbies & Leisure",
    8: "Jobs & Education",
    9: "Travel & Tourism",
    10: "Business & Industrial",
    11: "Arts & Entertainment",
    12: "Occasions & Gifts",
    13: "Health",
    14: "Dining & Nightlife",
    15: "Computers & Consumer Electronics",
    16: "Family & Community",
    17: "Real Estate",
    18: "Law & Government",
    19: "Internet & Telecom",
    20: "Finance",
    21: "Retailers & General Merchandise",
    22: "News Media & Publications",
  }

# task
[core/task/supervised]
model = microsoft/model/classification/bletchley/v3/image
dataset = core/dataset/ast
output_header = ['image']
postprocess_fn = core/postprocess/classification/score
writer = core/writer/csv

output_path = ${core/cli:output_file}

num_workers = 16
epochs = 20
log_freq = 100

test_batch_size = 4
