[core/cli]
task_name = core/task/supervised
test_file = ./test.tsv
cache_dir = ./cache
prompt_text = Write a long descriptive caption for this image in a formal tone.

# model
[core/model/generation/llava/llama_siglip]
pretrained_name = llava-v1.6-joycaption-2

num_beams = 2
max_gen_seq_length = 256

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    core/process/llava/llama_siglip/generation/inputs(
        "<|start_header_id|>system<|end_header_id|>\\n\\nCutting Knowledge Date: December 2023\\nToday Date: 26 July 2024\\n\\nYou are a helpful image captioner.<|eot_id|><|start_header_id|>user<|end_header_id|>\\n\\n<|reserved_special_token_70|><|reserved_special_token_69|><|reserved_special_token_71|>${core/cli:prompt_text}|eot_id|><|start_header_id|>assistant<|end_header_id|>\\n\\n", 
        core/process/image/read(image))
    '''
  ]

# process
[core/process/llava/llama_siglip]
pretrained_name = llava-v1.6-joycaption-2
max_seq_length = 48

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

[core/writer/csv]
nrows_per_sample = 1

# task
[core/task/supervised]
model = core/model/generation/llava/llama_siglip
dataset = core/dataset/ast

output_header = ['image']
postprocess_fn = core/postprocess/llava/llama_siglip/detokenize
writer = core/writer/csv

output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 8