[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.click.autonlp']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

[microsoft/adsplus/click/classification/autonlp]
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/adsplus/slab/pytorch_model.adsplus.click.autonlp.bin


# dataset
[core/dataset/ast/test]
names = ['rowid', 'query', 'ads', 'doc']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/tribert/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask")', 
    'microsoft/process/tribert/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask")',
    'microsoft/process/tribert/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask")',
  ]

# process
[microsoft/process/tribert]
max_seq_length = 20
max_n_letters = 20

[core/process/classification]
act_fn = sigmoid

# task
[core/task/supervised]
model = microsoft/adsplus/click/classification/autonlp
dataset = core/dataset/ast
output_header = ['rowid']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

num_workers = 8

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 64
