[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.slab.modeling_bert']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/slab/classification/bert]
pretrained_name = bert-base-uncased
num_classes = 10
label_gains = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/adsplus/slab/pytorch_model.bert.impression.v2.2.bin

# dataset
[core/dataset/ast]
names = ['title', 'doc', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = ['core/process/bert/classification(title, doc)', 'core/process/label/sequence([int(label) > 0, int(label) > 1, int(label) > 2, int(label) > 3, int(label) > 4, int(label) > 5, int(label) > 6, int(label) > 7, int(label) > 8, int(label) > 9], dtype="float")']

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = ['core/process/bert/classification(title, doc)', 'core/process/label(label, dtype="float")']

[core/dataset/ast/test]
names = ['title', 'doc']
data_files = ${core/cli:test_file}
preprocess_functions = ['core/process/bert/classification(title, doc)']

# process
[core/process/bert]
pretrained_name = bert-base-uncased
max_seq_length = 48

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/adsplus/slab/classification/bert
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/bce
score_fn = core/score/pearsonr_corr
monitor_fns = ['core/score/pearsonr_corr']

output_header = ['title', 'doc']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 128
dev_batch_size = 128
test_batch_size = 256
