[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.slab.bletchley_v1_click']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/slab/bletchley/v1/ranking]
config_type = 0.3B
projection_dim = 512
num_classes = 1
num_positions = 50
freeze_base_model = False
freeze_image_model = False
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/bletchley/v1/pytorch_model.0.3B.bin

# dataset
[core/dataset/ast]
# id, image, text
names = ['query', 'position', 'asset_type', 'asset', 'click_score', 'good_click_score', 'click']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(text=query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(text=asset, prefix="text_")',
    'core/process/number(position[2:] if position.lower().startswith("ml") else 0, dtype="int", key="pos_ids")',
    'core/process/number(int(asset_type == "Title"), dtype="int", key="type_ids")',
    'core/process/label(click)',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(text=query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(text=asset, prefix="text_")',
    'core/process/number(position[2:] if position.lower().startswith("ml") else 0, dtype="int", key="pos_ids")',
    'core/process/number(int(asset_type == "Title"), dtype="int", key="type_ids")',
    'core/process/label(click)',
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(text=query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(text=asset, prefix="text_")',
    'core/process/number(position[2:] if position.lower().startswith("ml") else 0, dtype="int", key="pos_ids")',
    'core/process/number(int(asset_type == "Title"), dtype="int", key="type_ids")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/adsplus/slab/bletchley/v1/ranking
dataset = core/dataset/ast
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['query', 'position', 'asset_type', 'asset', 'click_score', 'good_click_score', 'click']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 8
ckpt_freq = 5000

train_batch_size = 128
dev_batch_size = 128
test_batch_size = 128