[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.relevance.tribert']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/adsplus/relevance/classification/tribert/v8]
num_tasks = 4
num_classes = 1
reslayer_downscale_size = 64
pooltype = weight
sim4score = maxfeedforward
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/adsplus/relevance/tribert/pytorch_model.v8.bin

# dataset
[core/dataset/ast/test]
names = ['rowid', 'task', 'query', 'ads', 'doc']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask")',
    'microsoft/process/tribert/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask")',
    'microsoft/process/tribert/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask")',
  ]

# process
[microsoft/process/tribert]
max_seq_length = 20
max_n_letters = 20

# task
[core/task/supervised]
model = microsoft/adsplus/relevance/classification/tribert/v8
dataset = core/dataset/ast
output_header = ['rowid']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

num_workers = 8

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 64
