[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.models.llava']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/model/classification/llava/mistral_bletchley_v3]
pretrained_name = llava-v1.6-mistral-7b-bletchley-v3-2.5b

num_classes = 2

# dataset
[core/dataset/ast]
names = ['text', 'image', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = ['microsoft/process/llava/mistral_bletchley_v3/classification(text, core/process/image/read(image))', 'core/process/label(label)']

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = ['microsoft/process/llava/mistral_bletchley_v3/classification(text, core/process/image/read(image))', 'core/process/label(label)']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = ['microsoft/process/llava/mistral_bletchley_v3/classification(text, core/process/image/read(image))']

# process
[microsoft/process/llava/mistral_bletchley_v3]
pretrained_name = llava-v1.6-mistral-7b-bletchley-v3-2.5b
max_seq_length = 36

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

[core/writer/csv]
escapechar = \

# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/model/classification/llava/mistral_bletchley_v3
dataset = core/dataset/ast
loss_fn = core/loss/ce
score_fn = core/score/acc
monitor_fns = ['core/score/acc']
ckpt_freq = 2000

output_header = ['query', 'doc', 'label']
postprocess_fn = core/postprocess/classification/score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 1
dev_batch_size = 1
test_batch_size = 1