[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.mmdnn']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv
pretrained_weight_path = ./pytorch_model.bin

# model
[microsoft/model/classification/mmdnn/bletchley/v3/v2/intl]
query_config_type = 0.3B
offer_config_type = 0.8B
freeze_base_model = False
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast]
names = ['query', 'title', 'desc', 'image', 'label']

[core/dataset/ast/train]
names = ['query', 'title', 'desc', 'image', 'score']
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v3/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v3/text_classification(str(title) + " - " + str(desc), prefix="offer_")',
    'microsoft/process/bletchley/v3/image_classification(core/process/image/read(image))',
    'core/process/label(score, dtype="float")'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v3/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v3/text_classification(str(title) + " - " + str(desc), prefix="offer_")',
    'microsoft/process/bletchley/v3/image_classification(core/process/image/read(image))',
    'core/process/label(label)'
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v3/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v3/text_classification(str(title) + " - " + str(desc), prefix="offer_")',
    'microsoft/process/bletchley/v3/image_classification(core/process/image/read(image))'
  ]

# process
[microsoft/process/bletchley/v3]
max_seq_length = 36

[core/process/image]
http_url = http://0.0.0.0:11230/?image={0}

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/classification/mmdnn/bletchley/v3/v2/intl
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/mse
score_fn = core/score/auc
monitor_fns = ['core/score/auc', 'core/score/pr_auc']
output_header = ['query', 'title', 'desc', 'image', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
test_batch_size = 128
