[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.interrogators']
test_file = ./test.tsv
cache_dir = ./cache

# model
[microsoft/clip/ZeroClassification]
pretrained_name = clip-vit-large-patch14
image_col = image
do_reverse = False
classname = https://huggingface.co/datasets/fuliucansheng/unitorchblobfuse/resolve/main/data/ImageCategorys.txt

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/clip/image_classification(core/process/image/read(image))',
  ]

# process
[core/process/clip]
pretrained_name = clip-vit-large-patch14
max_seq_length = 77

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

[microsoft/clip/process/ZeroClassification]
classname = https://huggingface.co/datasets/fuliucansheng/unitorchblobfuse/resolve/main/data/ImageCategorys.txt

# task
[core/task/supervised]
model = microsoft/clip/ZeroClassification
dataset = core/dataset/ast
postprocess_fn = microsoft/clip/process/ZeroClassification/classname
output_header = ['image']
writer = core/writer/csv

output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128
