[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.pa', 'unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
pretrained_weight_path = ./pytorch_model.bin

# model
[microsoft/pa/pretrain/bletchley/v1/v2]
config_type = 0.3B
projection_dim = 512
gradient_checkpointing = True
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast]
# id, image, text
names = ['query', 'title', 'image']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="offer_")',
    'microsoft/process/bletchley/v1/image_classification(core/process/image/read(image))'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="offer_")',
    'microsoft/process/bletchley/v1/image_classification(core/process/image/read(image))'
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

[core/process/image]
http_url = http://0.0.0.0:11230/?image={0}

# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/pa/pretrain/bletchley/v1/v2
learning_rate = 0.0001
dataset = core/dataset/ast
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
