[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.decoration_relevance.tulr']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/model/pretrain/tulr/v6]
pretrained_name = tulrv6-base

# dataset
[core/dataset/ast]
names = ['query', 'doc', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/tulr/v6/pretrain(str(query), str(doc), label)'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/tulr/v6/pretrain(str(query), str(doc), label)'
  ]

# process
[microsoft/process/tulr/v6]
pretrained_name = tulrv6-base
max_seq_length = 48

# task
[core/task/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/model/pretrain/tulr/v6
dataset = core/dataset/ast
loss_fn = core/loss/loss
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

learning_rate = 0.00001

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 32
dev_batch_size = 32
test_batch_size = 64
