[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.bloom']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/model/generation/bloom/gptq]
pretrained_name = bloomz-560m
gptq_quant_config_path = configs/quantization/gptq.3bit.json
max_gen_seq_length = 128
num_beams = 2

# dataset
[core/dataset/ast/test]
names = ['instruction', 'encode']
data_files = ${core/cli:test_file}
preprocess_functions = ['microsoft/process/bloom/generation/inputs(instruction, encode)']

# process
[microsoft/process/bloom]
pretrained_name = bloomz-560m
max_seq_length = 256
max_gen_seq_length = 128

# task
[core/task/supervised]
model = microsoft/model/generation/bloom/gptq
dataset = core/dataset/ast
output_header = ['instruction', 'encode']
postprocess_fn = microsoft/postprocess/bloom/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 16
