[core/cli]
task_name = core/task/supervised
output_file = ./output.txt
test_file = ./test.tsv

# model
[core/model/segmentation/bria]
pretrained_weight_path = https://huggingface.co/briaai/RMBG-2.0/resolve/main/pytorch_model.bin

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = ['core/process/bria/segmentation/inputs(core/process/image/read(image))']

# process
[core/process/bria]
image_size = 1024

[core/process/image]
http_url = None

[core/process/segmentation]
output_folder = ${core/cli:cache_dir}

# task
[core/task/supervised]
model = core/model/segmentation/bria
dataset = core/dataset/ast

output_header = ['image']
postprocess_fn = core/postprocess/segmentation/mask
writer = core/writer/csv

output_path = ${core/cli:output_file}

num_workers = 16

test_batch_size = 4