[core/cli]
task_name = core/task/supervised
test_file = ./test.tsv
output_file = ./output.txt
prompt_text = Describe the image background.

# model
[core/model/generation/llava/mistral_clip]
pretrained_name = llava-v1.6-mistral-7b-hf
quant_config_path = configs/quantization/4bit.json
num_beams = 2
max_gen_seq_length = 256

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = ['core/process/llava/mistral_clip/generation/inputs("[INST] <image> ${core/cli:prompt_text} [/INST]", image)']

# process
[core/process/llava/mistral_clip]
pretrained_name = llava-v1.6-mistral-7b-hf
max_seq_length = 36

# task
[core/task/supervised]
model = core/model/generation/llava/mistral_clip
dataset = core/dataset/ast

output_header = ['image']
postprocess_fn = core/postprocess/llava/mistral_clip/detokenize
writer = core/writer/csv

output_path = ${core/cli:output_file}

test_batch_size = 16