[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.slab.retrieval.modeling_bletchley_v1_small']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/slab/retrieval/pretrain/text_bletchleyv1/small]
query_config_type = 0.3B
offer_config_type = 0.3B
freeze_base_model = False
gradient_checkpointing = True

query_num_hidden_layers = 3
query_hidden_size = 512
query_num_attention_heads = 8

# dataset
[core/dataset/ast]
names = ['query', 'slab','label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(slab, prefix="offer_")',
    'core/process/label(label)',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(slab, prefix="offer_")',
    'core/process/label(label)',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/adsplus/slab/retrieval/pretrain/text_bletchleyv1/small
dataset = core/dataset/ast
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 8
ckpt_freq = 5000

train_batch_size = 128
dev_batch_size = 128