[core/cli]
depends_libraries = [
    "unitorch_microsoft.china.alibaba.webui",
  ]
enabled_webuis = [
    "microsoft/webui/selection/image/getty",
    "microsoft/china/webui/ali1688",
  ]
device = 0

# pipeline
[microsoft/pipeline/selection/image/getty]
names = ["gettyid", "title", "desc", "url", "width", "height", "emb"]
emb_col = emb
show_cols = ["gettyid", "title", "desc", "url"]
image_cols = ["url"]
device = ${core/cli:device}

[microsoft/china/pipeline/ali1688]
names = ["globalofferid", "title", "desc", "url", "width", "height", "emb"]
emb_col = emb
show_cols = ["globalofferid", "title", "url"]
image_cols = ["url"]
device = ${core/cli:device}