[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.relevance.tribert']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/relevance/classification/tribert/v9/diffOnlineOffline]
pretrained_name = bert-base-multilingual-cased
config_path = adsplus/relevance/tribert/configs/config_prod_v9.json
offline_config_path = https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json
offline_pretrained_weight = https://huggingface.co/bert-base-multilingual-cased/resolve/main/pytorch_model.bin
online_model_freeze = True
num_tasks = 4
num_classes = 1
hidden_downscale_size = 64
reslayer_downscale_size = 64
pooltype = weight
sim4score = maxfeedforward

# dataset
[core/dataset/ast]
names = ['task', 'query', 'doc', 'ads', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/v9/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask", token_type_ids_name="query_token_type_ids", position_ids_name="query_position_ids")',
    'microsoft/process/tribert/v9/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask", token_type_ids_name="ads_token_type_ids", position_ids_name="ads_position_ids")',
    'microsoft/process/tribert/v9/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask", token_type_ids_name="doc_token_type_ids", position_ids_name="doc_position_ids")',
    'core/process/label(label, dtype="float")'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/v9/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask", token_type_ids_name="query_token_type_ids", position_ids_name="query_position_ids")',
    'microsoft/process/tribert/v9/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask", token_type_ids_name="ads_token_type_ids", position_ids_name="ads_position_ids")',
    'microsoft/process/tribert/v9/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask", token_type_ids_name="doc_token_type_ids", position_ids_name="doc_position_ids")',
    'core/process/label(label)'
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/v9/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask", token_type_ids_name="query_token_type_ids", position_ids_name="query_position_ids")',
    'microsoft/process/tribert/v9/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask", token_type_ids_name="ads_token_type_ids", position_ids_name="ads_position_ids")',
    'microsoft/process/tribert/v9/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask", token_type_ids_name="doc_token_type_ids", position_ids_name="doc_position_ids")',
  ]

# process
[microsoft/process/tribert/v9]
pretrained_name = bert-base-multilingual-cased
max_seq_length = 128

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/adsplus/relevance/classification/tribert/v9/diffOnlineOffline
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/mse
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['task', 'query', 'doc', 'ads']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

num_workers = 8
ckpt_freq = 3000

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 32
dev_batch_size = 32
test_batch_size = 64
