[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.adsplus.relevance.tribert']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/relevance/pretrain/tribert/v9/clip]
pretrained_name = bert-base-multilingual-cased
config_path = adsplus/relevance/tribert/configs/config_v9.json
use_all_gather = True
gradient_checkpointing = True
pooltype = weight
projection_dim = 64


# dataset
[core/dataset/ast]
names = ['task', 'query', 'doc', 'ads', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/v9/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask", token_type_ids_name="query_token_type_ids", position_ids_name="query_position_ids")',
    'microsoft/process/tribert/v9/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask", token_type_ids_name="ads_token_type_ids", position_ids_name="ads_position_ids")',
    'microsoft/process/tribert/v9/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask", token_type_ids_name="doc_token_type_ids", position_ids_name="doc_position_ids")',
    'core/process/label(label, dtype="float")'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/v9/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask", token_type_ids_name="query_token_type_ids", position_ids_name="query_position_ids")',
    'microsoft/process/tribert/v9/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask", token_type_ids_name="ads_token_type_ids", position_ids_name="ads_position_ids")',
    'microsoft/process/tribert/v9/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask", token_type_ids_name="doc_token_type_ids", position_ids_name="doc_position_ids")',
    'core/process/label(label)'
  ]

[core/dataset/ast/test]
names = ['task', 'query', 'ads', 'doc']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tribert/v9/classification(query, input_ids_name="query_input_ids", attention_mask_name="query_attention_mask", token_type_ids_name="query_token_type_ids", position_ids_name="query_position_ids")',
    'microsoft/process/tribert/v9/classification(ads, input_ids_name="ads_input_ids", attention_mask_name="ads_attention_mask", token_type_ids_name="ads_token_type_ids", position_ids_name="ads_position_ids")',
    'microsoft/process/tribert/v9/classification(doc, input_ids_name="doc_input_ids", attention_mask_name="doc_attention_mask", token_type_ids_name="doc_token_type_ids", position_ids_name="doc_position_ids")',
  ]

# process
[microsoft/process/tribert/v9]
pretrained_name = bert-base-multilingual-cased
max_seq_length = 12


# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/adsplus/relevance/pretrain/tribert/v9/clip
learning_rate = 0.0001
dataset = core/dataset/ast
score_fn = core/score/loss
monitor_fns = ['core/score/loss']
output_header = ['task', 'query', 'doc', 'ads']
writer = core/writer/csv

ckpt_freq = 3000

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
num_workers = 16
train_batch_size = 32
dev_batch_size = 32
test_batch_size = 64
