[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.tulr', 'unitorch_microsoft.msan.l1']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/msan/l1/classification/bletchley/v1]
config_type = 0.15B
projection_dim = 32
enable_tgs_features = True
enable_demands_features = True
enable_markets_features = False
enable_positions_features = False
output_ads_embeds = True
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/msan/pytorch_model.msan.l1.bletchley.v1.0.796.bin

# dataset
[core/dataset/ast]
names = ['rowid', 'user_id', 'tg_id', 'demand_type_id', 'market_id', 'ad_position_id', 'uet_events', 'search_events', 'ad_keyword', 'ad_title', 'ad_url', 'ad_desc', 'ad_sn', 'label']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
  '''
    microsoft/process/bletchley/v1/text_classification(
      (ad_keyword if ad_keyword else "") + " - " + (ad_title if ad_title else "") + " - " + (ad_desc if ad_desc else ""), 
      prefix="ads_",
    )
  '''
  ]

# process
[microsoft/msan/l1/process/bletchley/v1]
max_num_text = 10
max_seq_length = 64

[microsoft/process/bletchley/v1]
max_seq_length = 64

# task
[core/task/supervised]
model = microsoft/msan/l1/classification/bletchley/v1
dataset = core/dataset/ast
output_header = ['rowid']
postprocess_fn = microsoft/postprocess/classification/embedding/string
writer = core/writer/csv

num_workers = 16
postprocess_workers = 4

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 512
