[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr', 'unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.parquet
dev_file = ./dev.parquet
pretrained_weight_path = ./pytorch_model.bin

# model
[microsoft/vpr/pretrain/bletchley/v3/argus]
config_type = 0.3B
image_embed_dim = 100
projection_dim = 64
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast]
# image, text
template = parquet
features = datasets.Features({
    "id": datasets.Value("string"),
    "image": datasets.Sequence(datasets.Value("float32")),
    "text": datasets.Value("string"),
  })

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v3/text_classification(text)',
    'core/process/features(image, pad=0, num=100, dtype="float", key="image_embeds")'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v3/text_classification(text)',
    'core/process/features(image, pad=0, num=100, dtype="float", key="image_embeds")'
  ]


# process
[microsoft/process/bletchley/v3]
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/vpr/pretrain/bletchley/v3/argus
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
