[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.parquet
dev_file = ./dev.parquet

# model
[microsoft/vpr/pretrain/visualbert]
pretrained_name = visualbert-vqa-coco-pre
config_path = vpr/configs/visualbert.argus.json
image_embed_dim = 100
logit_scale_init_value = 1.6592
projection_dim = 100

# dataset
[core/dataset/ast]
# image, text
template = parquet
features = datasets.Features({"RawQuery": datasets.Value("string"), "QueryArgusEmb": datasets.Sequence(datasets.Value("float32")), "Title": datasets.Value("string"), "ImageURL": datasets.Value("string"), "OfferArgusEmb": datasets.Sequence(datasets.Value("float32"))})

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/vpr/process/visualbert/classification(RawQuery, prefix="query_")',
    'microsoft/vpr/process/visualbert/classification(Title, prefix="offer_")',
    'core/process/features(QueryArgusEmb, pad=0, num=100, dtype="float", shape=(1, 100), key="query_image_embeds")',
    'core/process/features(OfferArgusEmb, pad=0, num=100, dtype="float", shape=(1, 100), key="offer_image_embeds")'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/vpr/process/visualbert/classification(RawQuery, prefix="query_")',
    'microsoft/vpr/process/visualbert/classification(Title, prefix="offer_")',
    'core/process/features(QueryArgusEmb, pad=0, num=100, dtype="float", shape=(1, 100), key="query_image_embeds")',
    'core/process/features(OfferArgusEmb, pad=0, num=100, dtype="float", shape=(1, 100), key="offer_image_embeds")'
  ]

# process
[microsoft/vpr/process/visualbert]
pretrained_name = visualbert-vqa-coco-pre
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/vpr/pretrain/visualbert
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
