[core/cli]
depends_libraries = ['unitorch_microsoft.picasso.diffusion.scripts.outpainting']
script_name = microsoft/picasso/script/diffusion/outpainting
data_file = ./sample_200.tsv
image_folder = ./result_images
jsonl_file = ./output.jsonl
names = ['image']
prompt_col = None
prompt_text = simple background, realistic, extremely detailed, photorealistic, best quality
image_col = image
device = cpu

[microsoft/picasso/script/diffusion/outpainting]
image_col = image
api_endpoints = [
    "http://br1t44-s3-17:5050/core/fastapi/stable_flux/inpainting", 
    "http://br1t44-s3-17:5051/core/fastapi/stable_flux/inpainting", 
    "http://br1u43-s2-01:5050/core/fastapi/stable_flux/inpainting",
    ; "http://br1u43-s2-01:5051/core/fastapi/stable_flux/inpainting",
    "http://br1t43-s3-25.guest.corp.microsoft.com:5050/core/fastapi/stable_flux/inpainting",
    "http://br1t43-s3-25.guest.corp.microsoft.com:5051/core/fastapi/stable_flux/inpainting",
    "http://br1t45-s1-01:5050/core/fastapi/stable_flux/inpainting",
    ; "http://br1t45-s1-01:5051/core/fastapi/stable_flux/inpainting"
  ]
data_file = ${core/cli:data_file}
image_folder = ${core/cli:image_folder}
jsonl_file = ${core/cli:jsonl_file}
names = ${core/cli:names}
prompt_col = ${core/cli:prompt_col}
prompt_text = ${core/cli:prompt_text}
guidance_scale = 50
