[core/cli]
task_name = core/task/supervised
cache_dir = ./cache
from_ckpt_dir = ${core/cli:cache_dir}
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[core/model/generation/peft/lora/bloom]
pretrained_name = bloom-3b
lora_r = 4
max_gen_seq_length = 128
num_beams = 2

# dataset
[core/dataset/ast]
names = ['input', 'output']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = ['core/process/bloom/instruction/generation("Generate an attractive ad title & description for the input. # Input: {0} # Output:", input, output)']

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = ['core/process/bloom/instruction/generation/inputs("Generate an attractive ad title & description for the input. # Input: {0} # Output:", input)', 'core/process/bloom/generation/labels(output)']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = ['core/process/bloom/instruction/generation/inputs("Generate an attractive ad title & description for the input. # Input: {0} # Output:", input)']

# process
[microsoft/process/bloom]
pretrained_name = bloom-3b
max_seq_length = 256
max_gen_seq_length = 128

[core/writer/csv]
escapechar = \

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = core/model/generation/peft/lora/bloom
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/lm
score_fn = core/score/bleu
monitor_fns = ['core/score/bleu', 'core/score/rouge1', 'core/score/rouge2']
output_header = ['instruction', 'input', 'output']
postprocess_fn = core/postprocess/bloom/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

epochs = 100
log_freq = 100
save_checkpoint = best
save_optimizer = False
save_scheduler = False

train_batch_size = 4
dev_batch_size = 4
test_batch_size = 4
