[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv

# model
[microsoft/model/pretrain/bletchley/v1/text]
query_config_type = 0.3B
offer_config_type = 0.3B
projection_dim = 512
freeze_base_model = False
gradient_checkpointing = True
pretrained_weight_path = https://unitorchazureblob.blob.core.windows.net/shares/models/bletchley/v1/pytorch_model.0.3B.bin

# dataset
[core/dataset/ast]
names = ['user', 'query']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(user, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(query, prefix="doc_")',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(user, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(query, prefix="doc_")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/pretrain/bletchley/v1/text
dataset = core/dataset/ast
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 8
ckpt_freq = 5000

train_batch_size = 128
dev_batch_size = 128
