[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.tulr', 'unitorch_microsoft.msan.l1']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/msan/l1/classification/bletchley/v1/exp1/]
config_type = 0.15B
projection_dim = 32
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/bletchley/v1/pytorch_model.0.3B.bin

# dataset
[core/dataset/ast]
names = ['task', 'user_id', 'tg_id', 'demand_type_id', 'market_id', 'ad_position_id', 'uet_events', 'mv_searchquery_events', 'pre_ad_click_events', 'outlook_events', 'edge_events', 'organic_searchclick_events','ad_keyword', 'ad_title', 'ad_url', 'ad_desc', 'ad_sn', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
  '''
    microsoft/msan/l1/process/bletchley/v1/text_classification/v2(
      (uet_events.split(" #$$# ") if uet_events else []) + (mv_searchquery_events.split(" #$$# ") if mv_searchquery_events else []) + (pre_ad_click_events.split(" #$$# ") if pre_ad_click_events else []) + (outlook_events.split(" #$$# ") if outlook_events else []) + (edge_events.split(" #$$# ") if edge_events else []) + (organic_searchclick_events.split(" #$$# ") if organic_searchclick_events else []),
      prefix="user_",
    )
  ''',
  '''
    microsoft/process/bletchley/v1/text_classification(
      (ad_keyword if ad_keyword else "") + " - " + (ad_title if ad_title else "") + " - " + (ad_desc if ad_desc else ""), 
      prefix="ads_",
    )
  ''',
  'core/process/number(int(task == "click"), dtype="int", key="task")',
  'core/process/number(tg_id[1:], dtype="int", key="tg_ids")',
  'core/process/number(demand_type_id[1:], dtype="int", key="demand_ids")',
  'core/process/label(label)'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
  '''
    microsoft/msan/l1/process/bletchley/v1/text_classification/v2(
      (uet_events.split(" #$$# ") if uet_events else []) + (mv_searchquery_events.split(" #$$# ") if mv_searchquery_events else []) + (pre_ad_click_events.split(" #$$# ") if pre_ad_click_events else []) + (outlook_events.split(" #$$# ") if outlook_events else []) + (edge_events.split(" #$$# ") if edge_events else []) + (organic_searchclick_events.split(" #$$# ") if organic_searchclick_events else []),
      prefix="user_",
    )
  ''',
  '''
    microsoft/process/bletchley/v1/text_classification(
      (ad_keyword if ad_keyword else "") + " - " + (ad_title if ad_title else "") + " - " + (ad_desc if ad_desc else ""), 
      prefix="ads_",
    )
  ''',
  'core/process/number(int(task == "click"), dtype="int", key="task")',
  'core/process/number(tg_id[1:], dtype="int", key="tg_ids")',
  'core/process/number(demand_type_id[1:], dtype="int", key="demand_ids")',
  'core/process/label(label)'
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
  '''
    microsoft/msan/l1/process/bletchley/v1/text_classification/v2(
      (uet_events.split(" #$$# ") if uet_events else []) + (mv_searchquery_events.split(" #$$# ") if mv_searchquery_events else []) + (pre_ad_click_events.split(" #$$# ") if pre_ad_click_events else []) + (outlook_events.split(" #$$# ") if outlook_events else []) + (edge_events.split(" #$$# ") if edge_events else []) + (organic_searchclick_events.split(" #$$# ") if organic_searchclick_events else []),
      prefix="user_",
    )
  ''',
  '''
    microsoft/process/bletchley/v1/text_classification(
      (ad_keyword if ad_keyword else "") + " - " + (ad_title if ad_title else "") + " - " + (ad_desc if ad_desc else ""), 
      prefix="ads_",
    )
  ''',
  'core/process/number(int(task == "click"), dtype="int", key="task")',
  'core/process/number(tg_id[1:], dtype="int", key="tg_ids")',
  'core/process/number(demand_type_id[1:], dtype="int", key="demand_ids")',
  ]

# process
[microsoft/msan/l1/process/bletchley/v1]
max_num_text = 8
max_seq_length = 64

[microsoft/process/bletchley/v1]
max_seq_length = 64

[core/process/classification]
act_fn = sigmoid

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/msan/l1/classification/bletchley/v1/exp1/
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['task', 'user_id', 'tg_id', 'demand_type_id', 'market_id', 'ad_position_id', 'uet_events', 'mv_searchquery_events', 'pre_ad_click_events', 'outlook_events', 'edge_events', 'organic_searchclick_events','ad_keyword', 'ad_title', 'ad_url', 'ad_desc', 'ad_sn', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

num_workers = 8
ckpt_freq = 3000

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 64
dev_batch_size = 64
test_batch_size = 64
