model_list:
  - model_name: copilot-gemini-3.1-pro-preview
    litellm_params:
      model: github_copilot/gemini-3.1-pro-preview
  - model_name: copilot-gpt-5.4
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5.4
  - model_name: papyrus-gpt-image-15-eval
    litellm_params:
      model: openai/gpt-image-1.5
      api_base: https://westus2large.papyrus.binginternal.com
  - model_name: papyrus-gpt-4o-mini-transcribe-2025-12-15-eval
    litellm_params:
      model: openai/gpt-4o-mini-transcribe
      api_base: https://westus2large.papyrus.binginternal.com
  - model_name: gemini-3-pro-image-preview
    litellm_params:
      model: gemini/gemini-3-pro-image-preview
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  callbacks: ["papyrus.handler"]