[core/cli]
task_name = core/task/supervised
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[core/model/generation/bloom]
pretrained_name = bloomz-560m
max_gen_seq_length = 128

# dataset
[core/dataset/ast]
names = ['query', 'desturl', 'sd_title', 'sd_head', 'sd_paragraph', 'asset_type', 'asset']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    '''
    core/process/bloom/instruction/generation(
      "Generate a {0} for the given landing page. Requirements: {1}".format(asset_type, query).replace("{", "{{").replace("}", "}}") + " # Input: {0} # Output:",
      str(sd_title) + " - " + str(sd_head) + " " + str(sd_paragraph),
      asset,
    )
    '''
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    '''
    core/process/bloom/instruction/generation/inputs(
      "Generate a {0} for the given landing page. Requirements: {1}".format(asset_type, query).replace("{", "{{").replace("}", "}}") + " # Input: {0} # Output:",
      str(sd_title) + " - " + str(sd_head) + " " + str(sd_paragraph),
    )
    ''',
    'core/process/bloom/instruction/generation/labels(asset)'
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    core/process/bloom/instruction/generation/inputs(
      "Generate a {0} for the given landing page. Requirements: {1}".format(asset_type, query).replace("{", "{{").replace("}", "}}") + " # Input: {0} # Output:",
      str(sd_title) + " - " + str(sd_head) + " " + str(sd_paragraph),
    )
    '''
  ]

# process
[microsoft/process/bloom]
pretrained_name = bloomz-560m
max_seq_length = 256
max_gen_seq_length = 128

[core/writer/csv]
escapechar = \

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = core/model/generation/bloom
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/lm
score_fn = core/score/bleu
monitor_fns = ['core/score/bleu', 'core/score/rouge1', 'core/score/rouge2']
output_header = ['query', 'desturl', 'sd_title', 'sd_head', 'sd_paragraph', 'asset_type', 'asset']
postprocess_fn = core/postprocess/bloom/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

train_batch_size = 16
dev_batch_size = 16
test_batch_size = 16
