[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/model/pretrain/bletchley/v1/text]
query_config_type = 0.3B
doc_config_type = 0.3B
projection_dim = 512
freeze_base_model = False
gradient_checkpointing = True
output_doc_embed = True

# dataset
[core/dataset/ast]
names = ['doc']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(doc, prefix="doc_")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# task
[core/task/supervised]
model = microsoft/model/pretrain/bletchley/v1/text
dataset = core/dataset/ast

output_header = ['doc']
postprocess_fn = core/postprocess/classification/embedding/string
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 8

test_batch_size = 128
