[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.omnipixel.models']
output_file = ./output.txt
test_file = ./test.tsv

# model
[microsoft/omnipixel/model/image_reward]
config_path = https://huggingface.co/THUDM/ImageReward/resolve/main/med_config.json
pretrained_weight_path = https://huggingface.co/THUDM/ImageReward/resolve/main/ImageReward.pt


# dataset
[core/dataset/ast/test]
names = ['text', 'image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/omnipixel/process/image_reward/classification(text, core/process/image/read(image))',
  ]

# process
[core/process/image]
http_url = None

[core/process/classification]
act_fn = None

# task
[core/task/supervised]
model = microsoft/omnipixel/model/image_reward
dataset = core/dataset/ast
output_header = ['text', 'image']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

output_path = ${core/cli:output_file}

num_workers = 16

test_batch_size = 128
