[core/cli]
depends_libraries = ['unitorch_microsoft.models.kolors']
task_name = core/task/supervised

test_file = ./test.tsv
cache_dir = ./cache

# model
[microsoft/model/classification/kolors/mps]
pretrained_name = kolors-mps-overall

# dataset
[core/dataset/ast/test]
names = ['text', 'image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    core/process/kolors/mps/classification(
        text, 
        core/process/image/read(image), 
        "light, color, clarity, tone, style, ambiance, artistry, shape, face, hair, hands, limbs, structure, instance, texture, quantity, attributes, position, number, location, word, things.",
    )
    '''
  ]

# process
[core/process/kolors/mps]
pretrained_name = kolors-mps-overall

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

# task
[core/task/supervised]
model = microsoft/model/classification/kolors/mps
dataset = core/dataset/ast
output_header = ['text', 'image']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 32
