[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.omnipixel.models']
output_file = ./output.txt
test_file = ./test.tsv

# model
[microsoft/omnipixel/model/laion_clip/image]
pretrained_name = clip-vit-large-patch14


# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/clip/image_classification(core/process/image/read(image))',
  ]

# process
[core/process/clip]
pretrained_name = clip-vit-large-patch14
max_seq_length = 77

[core/process/image]
http_url = None

[core/process/classification]
act_fn = None

# task
[core/task/supervised]
model = microsoft/omnipixel/model/laion_clip/image
dataset = core/dataset/ast
output_header = ['image']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

output_path = ${core/cli:output_file}

num_workers = 16

test_batch_size = 128
