[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.msan.l1', 'unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv

# model
[microsoft/msan/l1/pretrain/bletchley/v1]
config_type = 0.3B
projection_dim = 32
gradient_checkpointing = True
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/bletchley/v1/pytorch_model.0.3B.bin

# dataset
[core/dataset/ast]
# id, image, text
names = ['uet_events', 'search_events', 'ad_keyword', 'ad_title', 'ad_desc']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    '''
    microsoft/msan/l1/process/bletchley/v1/text_classification/v2(
      (search_events.split(" #$$# ") if search_events else []) + (uet_events.split(" #$$# ") if uet_events else []),
      prefix="user_",
    )
    ''',
    '''
    microsoft/process/bletchley/v1/text_classification(
      (ad_keyword if ad_keyword else "") + " - " + (ad_title if ad_title else "") + " - " + (ad_desc if ad_desc else ""), 
      prefix="ads_",
    )
    ''',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    '''
    microsoft/msan/l1/process/bletchley/v1/text_classification/v2(
      (search_events.split(" #$$# ") if search_events else []) + (uet_events.split(" #$$# ") if uet_events else []),
      prefix="user_",
    )
    ''',
    '''
    microsoft/process/bletchley/v1/text_classification(
      (ad_keyword if ad_keyword else "") + " - " + (ad_title if ad_title else "") + " - " + (ad_desc if ad_desc else ""), 
      prefix="ads_",
    )
    ''',
  ]

# process
[microsoft/msan/l1/process/bletchley/v1]
max_num_text = 8
max_seq_length = 64

[microsoft/process/bletchley/v1]
max_seq_length = 64

# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/msan/l1/pretrain/bletchley/v1
learning_rate = 0.0001
dataset = core/dataset/ast
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 16

train_batch_size = 1024
dev_batch_size = 1024
