[core/cli]
depends_libraries = ["unitorch_microsoft.china.webui"]
enabled_webuis = [
    "microsoft/china/slab/webui/bloom",
    "microsoft/china/slab/webui/peft/bloom/lora",
    "core/webui/mistral",
  ]

# pipeline
[core/pipeline/bloom]
pretrained_name = bloomz-560m
max_seq_length = 256
max_gen_seq_length = 128
device = 0

[core/pipeline/peft/bloom/lora]
pretrained_name = bloomz-560m
max_seq_length = 512
max_gen_seq_length = 128
device = 0

[core/pipeline/mistral]
pretrained_name = mistral-7b
quant_config_path = configs/quantization/4bit.json
max_seq_length = 512
max_gen_seq_length = 128
device = 0

[core/pipeline/peft/mistral/lora]
pretrained_name = mistral-7b
quant_config_path = configs/quantization/4bit.json
max_seq_length = 512
max_gen_seq_length = 128
device = 0
