[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.models.minigpt4']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv
pretrained_weight_folder = ./MiniGPT-4-LLaMA-7B

# model
[microsoft/model/generation/peft/lora/minigpt4]
pretrained_name = minigpt4-7b
quant_config_path = configs/quantization/4bit.json
pretrained_weight_path = [
	'${core/cli:pretrained_weight_folder}/pytorch_model-00001-of-00002.bin',
	'${core/cli:pretrained_weight_folder}/pytorch_model-00002-of-00002.bin',
	'${core/cli:pretrained_weight_folder}/pytorch_model-00001-of-00006.bin',
	'${core/cli:pretrained_weight_folder}/pytorch_model.vicuna7b.bin',
  ]
gradient_checkpointing = True
decoder_end_token_id = [835, 2277, 2]
max_gen_seq_length = 36
num_beams = 2

# dataset
[core/dataset/ast]
names = ['image', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    '''
	core/process/minigpt4/generation(
		"Give the following image: <Img>ImageContent</Img>. You will be able to see the image once I provide it to you. Please answer my questions. ###Human: <Img>",
		"</Img> Classify the given image as either a Adult, Bad_Quality, Drug_and_Alchohol, Pharma, Religion, Sensitive, Weapon, Weight_loss, or Other. ###Assistant:",
		str(label) + " ###",
		core/process/image/read(image)
	)
	'''
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    '''
	core/process/minigpt4/generation/inputs(
		"Give the following image: <Img>ImageContent</Img>. You will be able to see the image once I provide it to you. Please answer my questions. ###Human: <Img>",
		"</Img> Classify the given image as either a Adult, Bad_Quality, Drug_and_Alchohol, Pharma, Religion, Sensitive, Weapon, Weight_loss, or Other. ###Assistant:",
		core/process/image/read(image)
	)
	''',
	'core/process/minigpt4/generation/labels(label)',
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
	core/process/minigpt4/generation/inputs(
		"Give the following image: <Img>ImageContent</Img>. You will be able to see the image once I provide it to you. Please answer my questions. ###Human: <Img>",
		"</Img> Classify the given image as either a Adult, Bad_Quality, Drug_and_Alchohol, Pharma, Religion, Sensitive, Weapon, Weight_loss, or Other. ###Assistant:",
		core/process/image/read(image)
	)
	''',
  ]

# process
[core/process/minigpt4]
pretrained_name = minigpt4-7b
max_prefix_seq_length = 64
max_suffix_seq_length = 128

[core/process/label]
map_dict = {
	"Other": 0,
	"Adult": 1,
	"Bad_Quality": 2,
	"Drug_and_Alchohol": 3,
	"Pharma": 4,
	"Religion": 5,
	"Sensitive": 6,
	"Weapon": 7,
	"Weight_loss": 8,
  }

[core/process/image]
http_url = http://0.0.0.0:11230/?image={0}

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

[core/writer/csv]
escapechar = \

# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/model/generation/peft/lora/minigpt4
dataset = core/dataset/ast
loss_fn = core/loss/lm
score_fn = core/score/rouge1
monitor_fns = ['core/score/rouge1']
output_header = ['image', 'label']
postprocess_fn = core/postprocess/minigpt4/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 8

train_batch_size = 4
dev_batch_size = 4
test_batch_size = 4

