[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.mps.mps_model', 'unitorch_microsoft.adsplus.mps.process']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv
label_text = negative

# model
[microsoft/adsplus/mps]
config_path = https://unitorchazureblob.blob.core.windows.net/shares/models/adsplus/mps/config.json
pretrained_weight_path = https://unitorchazureblob.blob.core.windows.net/shares/models/adsplus/mps/pytorch_model.bin


# dataset
[core/dataset/ast]
# id, image, text
names = ['id', 'prompt', 'image', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/mps/classification(prompt, "light, color, clarity, tone, style, ambiance, artistry, shape, face, hair, hands, limbs, structure, instance, texture, quantity, attributes, position, number, location, word, things.", image)',
    'core/process/label(label)',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/mps/classification(prompt, "light, color, clarity, tone, style, ambiance, artistry, shape, face, hair, hands, limbs, structure, instance, texture, quantity, attributes, position, number, location, word, things.", image)',
    'core/process/label(label)',
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/mps/classification(prompt, "light, color, clarity, tone, style, ambiance, artistry, shape, face, hair, hands, limbs, structure, instance, texture, quantity, attributes, position, number, location, word, things.", image)',
  ]

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/adsplus/mps
dataset = core/dataset/ast
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
loss_fn = core/loss/mse
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['id', 'prompt','image', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
test_batch_size = 128
