[core/cli]
depends_libraries = ["unitorch_microsoft.adinsights.webui"]
enabled_webuis = [
    "core/webui/mistral",
  ]
device = cpu

# pipeline
[core/pipeline/mistral]
quant_config_path = configs/quantization/4bit.json
max_seq_length = 512
max_gen_seq_length = 128
device = ${core/cli:device}
