[core/cli]
depends_libraries = ["unitorch_microsoft.adinsights.webui"]
enabled_webuis = [
    "microsoft/adinsights/webui/bloom",
    "microsoft/adinsights/webui/peft/mistral/lora",
    "core/webui/mistral",
    ; "core/webui/minigpt4",
  ]

# pipeline
[core/pipeline/bloom]
pretrained_name = bloomz-560m
max_seq_length = 256
max_gen_seq_length = 128
device = 0

[core/pipeline/mistral]
pretrained_name = mistral-7b
quant_config_path = configs/quantization/4bit.json
max_seq_length = 512
max_gen_seq_length = 128
device = 0

[core/pipeline/peft/mistral/lora]
pretrained_name = mistral-7b
quant_config_path = configs/quantization/4bit.json
max_seq_length = 512
max_gen_seq_length = 128
device = 0
