[core/cli]
task_name = core/task/supervised
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv
pretrained_weight_folder = ./MiniGPT-4-LLaMA

# model
[core/model/generation/minigpt4]
pretrained_name = minigpt4-13b
quant_config_path = configs/quantization/4bit.json
pretrained_weight_path = [
	'${core/cli:pretrained_weight_folder}/pytorch_model-00001-of-00002.bin',
	'${core/cli:pretrained_weight_folder}/pytorch_model-00002-of-00002.bin',
	'${core/cli:pretrained_weight_folder}/pytorch_model-00001-of-00006.bin',
	'${core/cli:pretrained_weight_folder}/pytorch_model.vicuna13b.bin',
  ]
gradient_checkpointing = True
decoder_end_token_id = [835, 2277]
max_gen_seq_length = 300
num_beams = 2

# dataset
[core/dataset/ast]
names = ['image', 'label']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
	core/process/minigpt4/generation/inputs(
		"Give the following image: <Img>ImageContent</Img>. You will be able to see the image once I provide it to you. Please answer my questions. ###Human: <Img>",
		"</Img> Classify the given image as either a Adult, Bad_Quality, Drug_and_Alchohol, Pharma, Religion, Sensitive, Weapon, Weight_loss, or Other. ###Assistant:",
		core/process/image/read(image)
	)
	''',
  ]

# process
[core/process/minigpt4]
pretrained_name = minigpt4-13b
max_prefix_seq_length = 64
max_suffix_seq_length = 128

[core/process/image]
http_url = http://0.0.0.0:11230/?image={0}

[core/writer/csv]
escapechar = \

# task
[core/task/supervised]
model = core/model/generation/minigpt4
dataset = core/dataset/ast
output_header = ['image', 'label']
postprocess_fn = core/postprocess/minigpt4/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 8

test_batch_size = 4

