[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.slab.retrieval.modeling_bletchley_v1']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/slab/retrieval/text_bletchleyv1/pairwise]
query_config_type = 0.3B
offer_config_type = 0.3B
num_class = 1
output_offer_embed = True

# dataset
[core/dataset/ast]
names = ['slab']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(slab, prefix="offer_")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# task
[core/task/supervised]
model = microsoft/adsplus/slab/retrieval/text_bletchleyv1/pairwise
dataset = core/dataset/ast

output_header = ['slab']
postprocess_fn = core/postprocess/classification/embedding/string
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 8
test_batch_size = 128