[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv

# model
[microsoft/vpr/classification/bert]
pretrained_name = bert-base-uncased
config_path = vpr/configs/bert.argus.json
num_hidden_layers = 3
image_embed_dim = 100

# dataset
[core/dataset/ast]
names = ['queryid', 'offerid', 'query', 'offer_argus_emb', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'core/process/bert/classification(query)',
    'core/process/features(offer_argus_emb.split(" ") if offer_argus_emb is not None else [], pad=0, num=100, dtype="float", shape=(100), key="image_embeds")',
    'core/process/label(label)'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'core/process/bert/classification(query)',
    'core/process/features(offer_argus_emb.split(" ") if offer_argus_emb is not None else [], pad=0, num=100, dtype="float", shape=(100), key="image_embeds")',
    'core/process/label(label)'
  ]

# process
[core/process/bert]
pretrained_name = bert-base-uncased
max_seq_length = 48

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/vpr/classification/bert
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']

output_header = ['queryid', 'offerid', 'query', 'offer_argus_emb', 'label']
postprocess_fn = core/postprocess/classification/embedding/string
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
