[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr', 'unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv

# model
[microsoft/vpr/classification/bletchley/v1/argus]
config_type = 0.3B
image_embed_dim = 100
projection_dim = 100

# dataset
[core/dataset/ast]
names = ['queryid', 'offerid', 'query', 'title', 'query_image', 'offer_image', 'query_argus_emb', 'offer_argus_emb', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="offer_")',
    'core/process/features(query_argus_emb.split(' ') if query_argus_emb is not None else [], pad=0, num=100, dtype="float", key="query_image_embeds")',
    'core/process/features(offer_argus_emb.split(' ') if offer_argus_emb is not None else [], pad=0, num=100, dtype="float", key="offer_image_embeds")',
    'core/process/label(label)'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="offer_")',
    'core/process/features(query_argus_emb.split(' ') if query_argus_emb is not None else [], pad=0, num=100, dtype="float", key="query_image_embeds")',
    'core/process/features(offer_argus_emb.split(' ') if offer_argus_emb is not None else [], pad=0, num=100, dtype="float", key="offer_image_embeds")',
    'core/process/label(label)'
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/vpr/classification/bletchley/v1/argus
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}

num_workers = 16

train_batch_size = 128
dev_batch_size = 128