[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr.diffusion']
from_ckpt_dir = ./cache
cache_dir = ./cache
image_folder = ./images
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/vpr/diffusion/stable/argus]
config_path = vpr/configs/diffusion/unet.argus.json
; text_config_path = vpr/configs/diffusion/text.argus.json
; vae_config_path = vpr/configs/diffusion/vae.argus.json
scheduler_config_path = vpr/configs/diffusion/scheduler.argus.json
freeze_text_encoder = True

# dataset
[core/dataset/ast]
names = ['text', 'argus_emb']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'core/process/clip/text_classification(text)',
    'core/process/features(argus_emb.split(" ") if argus_emb is not None else [], pad=0, num=100, dtype="float", shape=(1, 10, 10), key="argus_embeds")',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'core/process/clip/text_classification(text)',
    'core/process/features(argus_emb.split(" ") if argus_emb is not None else [], pad=0, num=100, dtype="float", shape=(1, 10, 10), key="argus_embeds")',
  ]

[core/dataset/ast/test]
names = ['text']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/clip/text_classification(text)',
  ]

# process
[core/process/clip]
pretrained_name = clip-vit-large-patch14
max_seq_length = 77

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/vpr/diffusion/stable/argus
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
score_fn = core/score/loss
monitor_fns = ['core/score/loss']
output_header = ['text']
postprocess_fn = core/postprocess/classification/embedding/string
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

train_batch_size = 4
dev_batch_size = 4
test_batch_size = 4