[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/model/matching/bletchley/v3]
config_type = 2.5B
projection_dim = 1024
pretrained_lora_weight_path = https://huggingface.co/datasets/fuliucansheng/unitorchblobfuse/resolve/main/models/adsplus/lora/bletchley/pytorch_model.v3.lora4.imagequality.flux.2409.bin
pretrained_weight_path = https://huggingface.co/datasets/fuliucansheng/unitorchblobfuse/resolve/main/models/bletchley/v3/pytorch_model.large.bin

# dataset

[core/dataset/ast/test]
names = ['image', 'label']
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    microsoft/process/bletchley/v3/classification(
      "worst quality, normal quality, low quality, low res, blurry, distortion, text, watermark, logo, banner, extra digits, cropped, jpeg artifacts, signature, username, error, sketch, duplicate, ugly, monochrome, horror, geometry, mutation, disgusting, bad anatomy, bad proportions, bad quality, deformed, disconnected limbs, out of frame, out of focus, dehydrated, disfigured, extra arms, extra limbs, extra hands, fused fingers, gross proportions, long neck, jpeg, malformed limbs, mutated, mutated hands, mutated limbs, missing arms, missing fingers, picture frame, poorly drawn hands, poorly drawn face, collage, pixel, pixelated, grainy, color aberration, amputee, autograph, bad illustration, beyond the borders, blank background, body out of frame, boring background, branding, cut off, dismembered, disproportioned, distorted, draft, duplicated features, extra fingers, extra legs, fault, flaw, grains, hazy, identifying mark, improper scale, incorrect physiology, incorrect ratio, indistinct, kitsch, low resolution, macabre, malformed, mark, misshapen, missing hands, missing legs, mistake, morbid, mutilated, off-screen, outside the picture, poorly drawn feet, printed words, render, repellent, replicate, reproduce, revolting dimensions, script, shortened, sign, split image, squint, storyboard, tiling, trimmed, unfocused, unattractive, unnatural pose, unreal engine, unsightly, written language",
      image
    )
    ''',
  ]

# process
[microsoft/process/bletchley/v3]
max_seq_length = 36

[core/process/classification]
act_fn = sigmoid

# task
[core/task/supervised]
model = microsoft/model/matching/bletchley/v3
dataset = core/dataset/ast

output_header = ['image', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 4
