[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.mmdnn']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv
pretrained_weight_path = ./pytorch_model.bin

# model
[microsoft/model/classification/mmdnn/bletchley/v1]
config_type = 0.3B
freeze_base_model = True
pretrained_weight_path = ${core/cli:pretrained_weight_path}
output_hidden_dim = 8
output_final_image_embed = True

# dataset
[core/dataset/ast/test]
data_files = ${core/cli:test_file}
names = ['rowid', 'seller', 'brand', 'image']
preprocess_functions = [
    'microsoft/process/bletchley/v1/image_classification(core/process/image/read(image))',
    'core/process/number(seller, dtype="int", key="seller_ids")',
    'core/process/number(brand, dtype="int", key="brand_ids")',
  ]

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

# task
[core/task/supervised]
model = microsoft/model/classification/mmdnn/bletchley/v1
dataset = core/dataset/ast

output_header = ['rowid']
postprocess_fn = core/postprocess/classification/embedding
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128
