[core/cli]
depends_libraries = [
    'unitorch_microsoft.models.diffusers',
    'unitorch_microsoft.apps',
  ]
enabled_services = [
    "microsoft/apps/spaces/picasso/bletchley/v1",
    "microsoft/apps/spaces/picasso/bletchley/v3",
    "microsoft/apps/spaces/picasso/siglip2",
    "microsoft/apps/spaces/picasso/swin/googlecate",
    "microsoft/apps/spaces/picasso/basnet",
    "microsoft/apps/spaces/picasso/detr",
    "microsoft/apps/spaces/gpt/image-15",
    "microsoft/apps/spaces/gemini/image",
  ]
device = cpu

# pipeline
[microsoft/models/bletchley/pipeline/v1/matching/v2]
device = ${core/cli:device}

[microsoft/models/bletchley/pipeline/v3/matching/v2]
device = ${core/cli:device}

[microsoft/models/siglip/pipeline/matching/v2]
device = ${core/cli:device}

[microsoft/apps/spaces/picasso/swin/googlecate]
device = ${core/cli:device}

[microsoft/picasso/pipeline/basnet]
device = ${core/cli:device}

[core/pipeline/detr]
device = ${core/cli:device}
