[core/cli]
home_folder = ./
picasso_folder = ${core/cli:home_folder}/picasso
device = 1

[core/pipeline/stable/inpainting]
max_seq_length = 77
enable_cpu_offload = True
enable_xformers = True
device = ${core/cli:device}

[core/fastapi/pipeline/controlnet/inpainting]
max_seq_length = 77
enable_cpu_offload = True
enable_xformers = True
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/image_control]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/inpainting]
device = ${core/cli:device}

# picasso spaces
[microsoft/spaces/picasso/examples]
sections = [
    "microsoft/spaces/picasso/examples/roi",
    "microsoft/spaces/picasso/examples/segmentation",
    ; "microsoft/spaces/picasso/examples/ocr",
    "microsoft/spaces/picasso/examples/outpainting",
    "microsoft/spaces/picasso/examples/bg_generation",
    ; "microsoft/spaces/picasso/examples/bg_type",
    ; "microsoft/spaces/picasso/examples/image_type",
  ]
titles = [
    "ROI",
    "Segmentation",
    ; "OCR",
    "Outpainting",
    "Background Generation",
    ; "Background Type",
    ; "Image Type",
  ]
descriptions = [
    "ROI involves identifying and analyzing a specific subset or area within a larger dataset, image, or environment that is of particular relevance or importance for further investigation or processing.",
    "Segmentation is the process of partitioning an image or dataset into meaningful segments or regions to facilitate analysis and interpretation.",
    ; "OCR",
    "Outpainting is the process of extending an image beyond its original boundaries, creatively filling in additional details and elements while maintaining visual coherence with the existing content.",
    "The Background Generation task involves creating diverse and contextually appropriate backgrounds for various applications, such as art, design, and virtual environments, to enhance visual storytelling and immersion.",
    ; "Background Type",
    ; "Image Type",
  ]

[microsoft/spaces/picasso/examples/roi]
data_file = ${core/cli:picasso_folder}/examples/ROI/data.tsv
result_file = ${core/cli:picasso_folder}/examples/ROI/result.tsv
names = ["group", "image", "result"]
image_cols = ["image", "result"]
group_col = group
checkbox = False
choices = ["Good", "Fair", "Bad"]

[microsoft/spaces/picasso/examples/segmentation]
data_file = ${core/cli:picasso_folder}/examples/Segmentation/data.tsv
result_file = ${core/cli:picasso_folder}/examples/Segmentation/result.tsv
names = ["group", "image", "mask", "result"]
image_cols = ["image", "mask", "result"]
group_col = group
checkbox = False
choices = ["Good", "Fair", "Bad"]

[microsoft/spaces/picasso/examples/outpainting]
data_file = ${core/cli:picasso_folder}/examples/Outpainting/data.tsv
result_file = ${core/cli:picasso_folder}/examples/Outpainting/result.tsv
names = ["group", "image", "result"]
image_cols = ["image", "result"]
group_col = group
checkbox = False
choices = ["Good", "Fair", "Bad"]

[microsoft/spaces/picasso/examples/bg_generation]
data_file = ${core/cli:picasso_folder}/examples/BackgroundGeneration/data.tsv
result_file = ${core/cli:picasso_folder}/examples/BackgroundGeneration/result.tsv
names = ["group", "image", "result"]
image_cols = ["image", "result"]
group_col = group
checkbox = False
choices = ["Good", "Fair", "Bad"]
