[core/cli]
depends_libraries = [
    'unitorch_microsoft.models.diffusers',
    'unitorch_microsoft.spaces.fastapis',
  ]
enabled_services = [
    "core/fastapi/bria",
    "core/fastapi/llava/mistral_clip",    
    "core/fastapi/llava/joycaption2",
    "core/fastapi/stable/inpainting",
    "core/fastapi/stable_flux/text2image",
    "core/fastapi/stable_flux/inpainting",
    "microsoft/spaces/fastapi/bletchley/v1",
    "microsoft/spaces/fastapi/bletchley/v3",
    "microsoft/spaces/fastapi/siglip2",
  ]
device = cpu

# pipeline
[core/pipeline/bria]
device = ${core/cli:device}

[core/pipeline/llava/mistral_clip]
device = ${core/cli:device}

[core/pipeline/llava/llama_siglip]
device = ${core/cli:device}

[core/fastapi/pipeline/stable/text2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable/inpainting]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/text2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/inpainting]
device = ${core/cli:device}

[microsoft/models/bletchley/pipeline/v1/matching/v2]
device = ${core/cli:device}

[microsoft/models/bletchley/pipeline/v3/matching/v2]
device = ${core/cli:device}

[microsoft/models/siglip/pipeline/matching/v2]
device = ${core/cli:device}