[core/cli]
depends_libraries = ['unitorch_microsoft.picasso.bad_crop_ruby']
task_name = core/task/supervised
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/picasso/model/bad_crop/ruby/v2]
max_seq_length = 48
labels = ["bad cropped, cut off, mutilated"]

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/picasso/process/bad_crop/ruby/v2/image_classification(core/process/image/read(image))',
  ]

# process
[microsoft/picasso/process/bad_crop/ruby/v2]
max_seq_length = 48

[core/process/image]
http_url = http://0.0.0.0:11230/core/fastapi/servers/zip_files/?file={0}

# task
[core/task/supervised]
model = microsoft/picasso/model/bad_crop/ruby/v2
dataset = core/dataset/ast
output_header = ['image']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

output_path = ${core/cli:cache_dir}/output.txt

num_workers = 4

test_batch_size = 4
