[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.adsplus.relevance.tulr']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/adsplus/relevance/classification/tulr/v6]
pretrained_name = tulrv6-xlarge
num_classes = 1

# dataset
[core/dataset/ast]
names = ['task', 'query', 'web4ads', 'keyword', 'adtitle', 'addesc', 'displayurl', 'decorationtype', 'decoration', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tulr/v6/classification(str(query) + " " + str(web4ads), str(keyword) + " " + str(adtitle) + " " + str(decoration) + " " + str(addesc))',
    'core/process/label(label)'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tulr/v6/classification(str(query) + " " + str(web4ads), str(keyword) + " " + str(adtitle) + " " + str(decoration) + " " + str(addesc))',
    'core/process/label(label)'
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/number(task, dtype="int", key="task")',
    'microsoft/process/tulr/v6/classification(str(query) + " " + str(web4ads), str(keyword) + " " + str(adtitle) + " " + str(decoration) + " " + str(addesc))',
  ]

# process
[microsoft/process/tulr/v6]
pretrained_name = tulrv6-xlarge
max_seq_length = 64

# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/adsplus/relevance/classification/tulr/v6
dataset = core/dataset/ast
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['task', 'query', 'web4ads', 'keyword', 'adtitle', 'addesc', 'displayurl', 'decorationtype', 'decoration', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

learning_rate = 0.00001

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 32
dev_batch_size = 32
test_batch_size = 64
