[core/cli]
enabled_services = [
    "core/fastapi/bria",
    "core/fastapi/llava/mistral_clip",    
    "core/fastapi/llava/joycaption2",
    "core/fastapi/stable/inpainting",
    "core/fastapi/stable_xl/text2image",
    "core/fastapi/stable_xl/inpainting",
    "core/fastapi/stable_flux/text2image",
    "core/fastapi/stable_flux/image2image",
    "core/fastapi/stable_flux/image_control",
    "core/fastapi/stable_flux/image_redux",
    "core/fastapi/stable_flux/inpainting",
    "core/fastapi/stable_flux/redux_inpainting",
  ]
device = cpu

# pipeline
[core/pipeline/bria]
device = ${core/cli:device}

[core/pipeline/llava/mistral_clip]
device = ${core/cli:device}

[core/pipeline/llava/llama_siglip]
device = ${core/cli:device}

[core/fastapi/pipeline/stable/text2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable/inpainting]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_xl/text2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_xl/inpainting]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/text2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/image2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/image_control]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/image_redux]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/inpainting]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/redux_inpainting]
device = ${core/cli:device}
