[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/model/matching/peft/lora/bletchley/v1/text]
query_config_type = 2.5B
doc_config_type = 2.5B
projection_dim = 2048
lora_r = 4
pretrained_weight_path = https://unitorchazureblob.blob.core.windows.net/shares/models/bletchley/v1/pytorch_model.2.5B.bin

# dataset
[core/dataset/ast]
# id, image, text
names = ['query', 'title', 'image', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="doc_")',
    'core/process/label(label)',
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="doc_")',
    'core/process/label(label)',
  ]


[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query, prefix="query_")',
    'microsoft/process/bletchley/v1/text_classification(title, prefix="doc_")'
  ]

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/matching/peft/lora/bletchley/v1/text
dataset = core/dataset/ast
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['query', 'title', 'image', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16
epochs = 20
log_freq = 10

train_batch_size = 4
dev_batch_size = 4
