[core/cli]
depends_libraries = [
    "unitorch_microsoft.picasso.diffusion.controlnet_flux",
  ]
task_name = core/task/supervised
from_ckpt_dir = ./cache
cache_dir = ./cache
output_folder = ./images
test_file = ./test.tsv

# model
[microsoft/picasso/diffusion/text2image/controlnet_flux]
pretrained_name = stable-flux-dev
pretrained_controlnet_names = stable-flux-controlnet-dev-union-pro
seed = 42
guidance_scale = 3.5
num_infer_timesteps = 50
controlnet_conditioning_scale = [0.6, 0.2]
controlnet_conditioning_mode = [0, 2]

# dataset
[core/dataset/ast/test]ca
names = ['text', 'canny_image', 'depth_image']
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    core/process/diffusion/controlnet_flux/text2image/inputs(
      text,
      [core/process/image/read(canny_image), core/process/image/read(depth_image)]
    )
    ''',
  ]

# process
[core/process/diffusion/controlnet_flux]
pretrained_name = stable-flux-dev
max_seq_length = 77
image_size = (1024, 1024)

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

[core/process/diffusion]
output_folder = ${core/cli:output_folder}

# task
[core/task/supervised]
model = microsoft/picasso/diffusion/text2image/controlnet_flux
dataset = core/dataset/ast
output_header = ['text']
postprocess_fn = core/postprocess/diffusion/image
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 1
