[core/cli]
task_name = core/task/supervised
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[core/model/generation/llava/mistral_clip]
pretrained_name = llava-v1.6-mistral-7b-hf
quant_config_path = configs/quantization/4bit.json
num_beams = 2
max_gen_seq_length = 256

# dataset
[core/dataset/ast/test]
names = ['image']
data_files = ${core/cli:test_file}
preprocess_functions = ['core/process/llava/mistral_clip/generation/inputs("[INST] <image> Describe this image in details. [/INST]", core/process/image/read(image))']

# process
[core/process/llava/mistral_clip]
pretrained_name = llava-v1.6-mistral-7b-hf
max_seq_length = 36

[core/process/image]
http_url = http://0.0.0.0:11230/?file={0}

# task
[core/task/supervised]
model = core/model/generation/llava/mistral_clip
dataset = core/dataset/ast

output_header = ['image']
postprocess_fn = core/postprocess/llava/mistral_clip/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

test_batch_size = 16