[core/cli]
task_name = core/task/deepspeed/supervised
depends_libraries = ['unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/model/matching/bletchley/v3]
config_type = 2.5B
projection_dim = 2048
gradient_checkpointing = True
pretrained_weight_path = https://unitorchblobfuse.blob.core.windows.net/shares/models/bletchley/v3/pytorch_model.large.bin
output_image_embed = True


[core/dataset/ast/test]
data_files = ${core/cli:test_file}
names = ['id', 'image']
preprocess_functions = [
    'microsoft/process/bletchley/v3/image_classification(core/process/image/read(image))',
  ]

[core/process/image]
http_url = http://0.0.0.0:11230/?image={0}

# process
[microsoft/process/bletchley/v3]
max_seq_length = 36

# task
[core/task/deepspeed/supervised]
config_path = configs/deepspeed/adamw.json
model = microsoft/model/matching/bletchley/v3

dataset = core/dataset/ast

output_header = ['id']
postprocess_fn = core/postprocess/classification/embedding/string
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128
