[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.adsplus.image.bletchley_v1_click']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[microsoft/adsplus/image/bletchley/v1/click/embeddingscore]
config_type = 0.3B
projection_dim = 512
num_classes = 1
num_positions = 50
pretrained_weight_path = https://unitorchazureblob.blob.core.windows.net/shares/models/bletchley/v1/pytorch_model.0.3B.bin

# dataset
[core/dataset/ast]
names = ['query', 'image', 'image_emb']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(query)',
    'core/process/features(image_emb.split(" "), dtype="float", key="image_embeds")',
    'core/process/number(1, dtype="int", key="pos_ids")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# task
[core/task/supervised]
model = microsoft/adsplus/image/bletchley/v1/click/embeddingscore
dataset = core/dataset/ast

output_header = ['query', 'image']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128