[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.tulr']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv

# model
[microsoft/model/classification/tulr/v6]
pretrained_name = tulrv6-base
num_classes = 1

# dataset
[core/dataset/ast]
names = ['user_id', 'demand_type_id', 'market_id', 'ad_position_id', 'uet_events', 'search_events', 'search_click_events', 'native_click_events', 'edge_search_query_events', 'edge_page_title_events', 'ad_keyword', 'ad_title', 'ad_url', 'ad_desc', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = ['microsoft/process/tulr/v6/classification(ad_title, ad_desc)', 'core/process/label(label)']

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = ['microsoft/process/tulr/v6/classification(ad_title, ad_desc)', 'core/process/label(label)']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = ['microsoft/process/tulr/v6/classification(ad_title, ad_desc)']

# process
[microsoft/process/tulr/v6]
pretrained_name = tulrv6-base
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/classification/tulr/v6
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/bce
score_fn = core/score/auc
monitor_fns = ['core/score/auc']
output_header = ['user_id', 'demand_type_id', 'market_id', 'ad_position_id', 'uet_events', 'search_events', 'search_click_events', 'native_click_events', 'edge_search_query_events', 'edge_page_title_events', 'ad_keyword', 'ad_title', 'ad_url', 'ad_desc', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

num_workers = 8
ckpt_freq = 3000

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt
train_batch_size = 32
dev_batch_size = 32
test_batch_size = 64
