[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.tulr']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv

# model
[microsoft/model/pretrain/tulr/v6]
pretrained_name = tulrv6-base
use_nsp_loss = False

# dataset
[core/dataset/ast]
names = ['query', 'doc', 'label']

[core/dataset/ast/train]
data_files = ${core/cli:train_file}
preprocess_functions = ['microsoft/process/tulr/v6/pretrain(query, doc, label)']

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
preprocess_functions = ['microsoft/process/tulr/v6/pretrain(query, doc, label)']

# process
[microsoft/process/tulr/v6]
pretrained_name = tulrv6-base
max_seq_length = 36

# optim
[core/optim/adamw]
learning_rate = 0.00001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/pretrain/tulr/v6
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/loss
score_fn = core/score/loss
monitor_fns = ['core/score/loss']

num_workers = 8
ckpt_freq = 3000

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
train_batch_size = 32
dev_batch_size = 32
