[core/cli]
depends_libraries = [
    'unitorch_microsoft.dlis.clip',
  ]
enabled_services = [
    "microsoft/dlis/fastapi/clip/matching"
  ]
device = cpu

# pipeline
[microsoft/dlis/pipeline/clip/matching]
device = ${core/cli:device}
