[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr', 'unitorch_microsoft.models.bletchley']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv
pretrained_weight_path = ./pytorch_model.bin

# model
[microsoft/vpr/classification/bletchley/v1/argus]
config_type = 0.3B
image_embed_dim = 100
projection_dim = 64
output_offer_embed = True
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast]
names = ['queryid', 'offerid', 'query', 'title', 'query_image', 'offer_image', 'query_argus_emb', 'offer_argus_emb', 'label']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(title, prefix="offer_")',
    'core/process/features(offer_argus_emb.split(' ') if offer_argus_emb is not None else [], pad=0, num=100, dtype="float", key="offer_image_embeds")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

# task
[core/task/supervised]
model = microsoft/vpr/classification/bletchley/v1/argus
dataset = core/dataset/ast

output_header = ['queryid', 'offerid']
post_process_fn = core/postprocess/classification/embedding
writer_fn = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128
