[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.vpr']
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv
pretrained_weight_path = https://huggingface.co/datasets/fuliucansheng/unitorchblobfuse/resolve/main/models/pytorch_model.visualbert.v2.pretrain.bin

# model
[microsoft/vpr/classification/visualbert/v2]
pretrained_name = visualbert-vqa-coco-pre
config_path = vpr/configs/visualbert.argus.json
image_embed_dim = 100
projection_dim = 100
output_offer_embed = True
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast]
names = ['queryid', 'offerid', 'query', 'title', 'query_image', 'offer_image', 'query_argus_emb', 'offer_argus_emb', 'label']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    'core/process/features(offer_argus_emb.split(' ') if offer_argus_emb is not None else [], pad=0, num=100, dtype="float", shape=(1, 100), key="offer_image_embeds")',
  ]

# process
[microsoft/vpr/process/visualbert]
pretrained_name = visualbert-vqa-coco-pre
max_seq_length = 36

# task
[core/task/supervised]
model = microsoft/vpr/classification/visualbert/v2
dataset = core/dataset/ast

output_header = ['queryid', 'offerid']
postprocess_fn = core/postprocess/classification/embedding
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

test_batch_size = 128
