[core/cli]
task_name = core/task/supervised
depends_libraries = ['unitorch_microsoft.models.mmdnn']
from_ckpt_dir = ./cache
cache_dir = ./cache
train_file = ./train.tsv
dev_file = ./dev.tsv
test_file = ./test.tsv
pretrained_weight_path = ./pytorch_model.bin

# model
[microsoft/model/classification/mmdnn/v6/bletchley/v1]
config_type = 0.3B
num_query_layers = 3
pretrained_weight_path = ${core/cli:pretrained_weight_path}

# dataset
[core/dataset/ast/train]
data_files = ${core/cli:train_file}
names = ['rowid', 'query', 'qu', 'web4ads', 'title', 'desc', 'image', 'seller', 'brand', 'score']
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(str(query) + " - " + str(web4ads))',
    'microsoft/process/bletchley/v1/image_classification(core/process/image/read(image))',
    'core/process/number(seller, dtype="int", key="seller_ids")',
    'core/process/number(brand, dtype="int", key="brand_ids")',
    'core/process/label(score, dtype="float")'
  ]

[core/dataset/ast/dev]
data_files = ${core/cli:dev_file}
names = ['rowid', 'query', 'qu', 'web4ads', 'title', 'desc', 'image', 'seller', 'brand', 'label']
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(str(query) + " - " + str(web4ads))',
    'microsoft/process/bletchley/v1/image_classification(core/process/image/read(image))',
    'core/process/number(seller, dtype="int", key="seller_ids")',
    'core/process/number(brand, dtype="int", key="brand_ids")',
    'core/process/label(label)'
  ]

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
names = ['rowid', 'query', 'qu', 'web4ads', 'title', 'desc', 'image', 'seller', 'brand', 'label']
preprocess_functions = [
    'microsoft/process/bletchley/v1/text_classification(str(query) + " - " + str(web4ads))',
    'microsoft/process/bletchley/v1/image_classification(core/process/image/read(image))',
    'core/process/number(seller, dtype="int", key="seller_ids")',
    'core/process/number(brand, dtype="int", key="brand_ids")',
  ]

# process
[microsoft/process/bletchley/v1]
max_seq_length = 36

[core/process/image]
http_url = http://0.0.0.0:11230/?image={0}

# optim
[core/optim/adamw]
learning_rate = 0.0001

# scheduler
[core/scheduler/linear_warmup]
num_warmup_rate = 0.001

# task
[core/task/supervised]
model = microsoft/model/classification/mmdnn/v6/bletchley/v1
optim = core/optim/adamw
scheduler = core/scheduler/linear_warmup
dataset = core/dataset/ast
loss_fn = core/loss/mse
score_fn = core/score/pr_auc
monitor_fns = ['core/score/auc', 'core/score/pr_auc']
output_header = ['rowid', 'query', 'qu', 'web4ads', 'title', 'desc', 'image', 'seller', 'brand', 'label']
postprocess_fn = core/postprocess/classification/binary_score
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
to_ckpt_dir = ${core/cli:cache_dir}
output_path = ${core/cli:cache_dir}/output.txt

num_workers = 16

train_batch_size = 128
dev_batch_size = 128
test_batch_size = 128
